In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("survey_results_public.csv")

In [5]:
df

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,...,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
2,3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
3,4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
4,5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73263,73264,I am a developer by profession,"Employed, full-time",Fully remote,Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Udemy,8,...,30-60 minutes a day,Less than 15 minutes a day,Just right,DevOps function;Microservices;Developer portal...,Yes,Yes,Yes,Too long,Easy,NaN
73264,73265,I am a developer by profession,"Employed, full-time",Full in-person,Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,Coursera;Udemy;Udacity,6,...,15-30 minutes a day,60-120 minutes a day,Very long,None of these,No,Yes,Yes,Too long,Easy,NaN
73265,73266,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby;School or academic work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Programming Games;Stac...,Udemy;Codecademy;Pluralsight;edX,42,...,30-60 minutes a day,60-120 minutes a day,Just right,None of these,No,No,No,Appropriate in length,Easy,NaN
73266,73267,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;On the job training,NaN,NaN,50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
73267,73268,"I used to be a developer by profession, but no...","Independent contractor, freelancer, or self-em...",Fully remote,Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,Udemy;Pluralsight,16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN

In [6]:
df.shape

(73268, 79)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73268 entries, 0 to 73267
Data columns (total 79 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   ResponseId                      73268 non-null  int64
 1   MainBranch                      73268 non-null  object
 2   Employment                      71709 non-null  object
 3   RemoteWork                      58958 non-null  object
 4   CodingActivities                58899 non-null  object
 5   EdLevel                         71571 non-null  object
 6   LearnCode                       71580 non-null  object
 7   LearnCodeOnline                 50685 non-null  object
 8   LearnCodeCoursesCert            29389 non-null  object
 9   YearsCode                       71331 non-null  object
 10  YearsCodePro                    51833 non-null  object
 11  DevType                         61302 non-null  object
 12  OrgSize                         51039 non-null  object
 13  PurchaseInfluence               50969 non-null  object
 14  BuyNewTool                      67963 non-null  object
 15  Country                         71771 non-null  object
 16  Currency                        51264 non-null  object
 17  CompTotal                       38422 non-null  float64
 18  CompFreq                        44425 non-null  object
 19  LanguageHaveWorkedWith          70975 non-null  object
 20  LanguageWantToWorkWith          67027 non-null  object
 21  DatabaseHaveWorkedWith          60121 non-null  object
 22  DatabaseWantToWorkWith          51014 non-null  object
 23  PlatformHaveWorkedWith          49924 non-null  object
 24  PlatformWantToWorkWith          40415 non-null  object
 25  WebframeHaveWorkedWith          53544 non-null  object
 26  WebframeWantToWorkWith          46122 non-null  object
 27  MiscTechHaveWorkedWith          44992 non-null  object
 28  MiscTechWantToWorkWith          36810 non-null  object
 29  ToolsTechHaveWorkedWith         54171 non-null  object
 30  ToolsTechWantToWorkWith         46566 non-null  object
 31  NEWCollabToolsHaveWorkedWith    70347 non-null  object
 32  NEWCollabToolsWantToWorkWith    64108 non-null  object
 33  OpSysProfessional use           65503 non-null  object
 34  OpSysPersonal use               70963 non-null  object
 35  VersionControlSystem            71379 non-null  object
 36  VCInteraction                   68156 non-null  object
 37  VCHostingPersonal use           0 non-null      float64
 38  VCHostingProfessional use       0 non-null      float64
 39  OfficeStackAsyncHaveWorkedWith  46223 non-null  object
 40  OfficeStackAsyncWantToWorkWith  32072 non-null  object
 41  OfficeStackSyncHaveWorkedWith   62128 non-null  object
 42  OfficeStackSyncWantToWorkWith   47688 non-null  object
 43  Blockchain                      71071 non-null  object
 44  NEWSOSites                      71365 non-null  object
 45  SOVisitFreq                     70961 non-null  object
 46  SOAccount                       71572 non-null  object
 47  SOPartFreq                      58229 non-null  object
 48  SOComm                          71408 non-null  object
 49  Age                             70946 non-null  object
 50  Gender                          70853 non-null  object
 51  Trans                           70315 non-null  object
 52  Sexuality                       66565 non-null  object
 53  Ethnicity                       69474 non-null  object
 54  Accessibility                   67244 non-null  object
 55  MentalHealth                    66447 non-null  object
 56  TBranch                         52670 non-null  object
 57  ICorPM                          36283 non-null  object
 58  WorkExp                         36769 non-null  float64
 59  Knowledge_1                     35804 non-null  object
 60  Knowledge_2                     34973 non-null  object
 61  Knowledge_3                     35133 non-null  object
 62  Knowledge_4                     35097 non-null  object
 63  Knowledge_5                     35014 non-null  object
 64  Knowledge_6                     34991 non-null  object
 65  Knowledge_7                     34977 non-null  object
 66  Frequency_1                     35371 non-null  object
 67  Frequency_2                     35344 non-null  object
 68  Frequency_3                     34515 non-null  object
 69  TimeSearching                   36198 non-null  object
 70  TimeAnswering                   36022 non-null  object
 71  Onboarding                      35679 non-null  object
 72  ProfessionalTech                34906 non-null  object
 73  TrueFalse_1                     35819 non-null  object
 74  TrueFalse_2                     35715 non-null  object
 75  TrueFalse_3                     35749 non-null  object
 76  SurveyLength                    70444 non-null  object
 77  SurveyEase                      70508 non-null  object
 78  ConvertedCompYearly             38071 non-null  float64
dtypes: float64(5), int64(1), object(73)
memory usage: 44.2+ MB

In [8]:
schema_df=pd.read_csv("survey_results_schema.csv")

In [9]:
schema_df

,qid,qname,question,force_resp,type,selector
0,QID16,S0,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
1,QID12,MetaInfo,Browser Meta Info,False,Meta,Browser
2,QID1,S1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
3,QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
4,QID296,Employment,Which of the following best describes your cur...,False,MC,MAVR
...,...,...,...,...,...,...
74,QID290,Frequency_2,Interacting with people outside of your immedi...,NaN,MC,MAVR
75,QID290,Frequency_3,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR
76,QID294,TrueFalse_1,Are you involved in supporting new hires durin...,NaN,MC,MAVR
77,QID294,TrueFalse_2,Do you use learning resources provided by your...,NaN,MC,MAVR
78,QID294,TrueFalse_3,Does your employer give you time to learn new ...,NaN,MC,MAVR

In [10]:
schema_df.shape

(79, 6)

In [11]:
pd.set_option('display.max_columns', 79)
pd.set_option('display.max_rows', 79)

In [12]:
df.head()

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Canada,CAD\tCanadian dollar,NaN,NaN,JavaScript;TypeScript,Rust;TypeScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,macOS,Windows Subsystem for Linux (WSL),Git,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,Daily or almost daily,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
2,3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,5,Data scientist or machine learning specialist;...,20 to 99 employees,I have some influence,NaN,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,32000.0,Yearly,C#;C++;HTML/CSS;JavaScript;Python,C#;C++;HTML/CSS;JavaScript;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,Angular.js,Angular;Angular.js,Pandas,.NET,NaN,NaN,Notepad++;Visual Studio,Notepad++;Visual Studio,Windows,Windows,Git,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Very unfavorable,Collectives on Stack Overflow;Stack Overflow;S...,Multiple times per day,Yes,Multiple times per day,Neutral,25-34 years old,Man,No,Bisexual,White,None of the above,"I have a mood or emotional disorder (e.g., dep...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
3,4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,17,"Developer, full-stack",100 to 499 employees,I have some influence,Other (please specify):,Israel,ILS\tIsraeli new shekel,60000.0,Monthly,C#;JavaScript;SQL;TypeScript,C#;SQL;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,.NET,.NET,NaN,NaN,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Jira Work Management;Trello,Jira Work Management;Trello,Slack;Zoom,Slack;Zoom,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,A few times per week,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
4,5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,3,"Developer, front-end;Developer, full-stack;Dev...",20 to 99 employees,I have some influence,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,NaN,NaN,C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,C#;Elixir;F#;Go;JavaScript;Rust;TypeScript,Cloud Firestore;Elasticsearch;Microsoft SQL Se...,Cloud Firestore;Elasticsearch;Firebase Realtim...,Firebase;Microsoft Azure,Firebase;Microsoft Azure,Angular;ASP.NET;ASP.NET Core ;jQuery;Node.js,Angular;ASP.NET Core ;Blazor;Node.js,.NET,.NET;Apache Kafka,npm,Docker;Kubernetes,Notepad++;Visual Studio;Visual Studio Code;Xcode,Rider;Visual Studio;Visual Studio Code,Windows,macOS;Windows,Git;Other (please specify):,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,NaN,Unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",25-34 years old,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN

In [13]:
schema_df.head()

,qid,qname,question,force_resp,type,selector
0,QID16,S0,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
1,QID12,MetaInfo,Browser Meta Info,False,Meta,Browser
2,QID1,S1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
3,QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
4,QID296,Employment,Which of the following best describes your cur...,False,MC,MAVR

In [14]:
people = {
    "first": ["Corey", 'Jane', 'John'], 
    "last": ["Schafer", 'Doe', 'Doe'], 
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [15]:
dict_df=pd.DataFrame(people)

In [16]:
dict_df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [17]:
dict_df["email"]

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: object

In [18]:
dict_df[["email","last"]]

                     email     last
0  CoreyMSchafer@gmail.com  Schafer
1        JaneDoe@email.com      Doe
2        JohnDoe@email.com      Doe

In [19]:
dict_df.iloc[0]

first                      Corey
last                     Schafer
email    CoreyMSchafer@gmail.com
Name: 0, dtype: object

In [20]:
dict_df.iloc[[0,1]]

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com

In [21]:
dict_df.iloc[[0,1],2]

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
Name: email, dtype: object

In [22]:
dict_df.loc[0]

first                      Corey
last                     Schafer
email    CoreyMSchafer@gmail.com
Name: 0, dtype: object

In [23]:
dict_df.loc[[0,1]]

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com

In [24]:
dict_df.loc[[0,1],["email"]]

                     email
0  CoreyMSchafer@gmail.com
1        JaneDoe@email.com

In [25]:
dict_df.loc[[0,1],["email","last"]]

                     email     last
0  CoreyMSchafer@gmail.com  Schafer
1        JaneDoe@email.com      Doe

In [26]:
df.columns

Index(['ResponseId', 'MainBranch', 'Employment', 'RemoteWork',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'LearnCodeCoursesCert', 'YearsCode', 'YearsCodePro', 'DevType',
       'OrgSize', 'PurchaseInfluence', 'BuyNewTool', 'Country', 'Currency',
       'CompTotal', 'CompFreq', 'LanguageHaveWorkedWith',
       'LanguageWantToWorkWith', 'DatabaseHaveWorkedWith',
       'DatabaseWantToWorkWith', 'PlatformHaveWorkedWith',
       'PlatformWantToWorkWith', 'WebframeHaveWorkedWith',
       'WebframeWantToWorkWith', 'MiscTechHaveWorkedWith',
       'MiscTechWantToWorkWith', 'ToolsTechHaveWorkedWith',
       'ToolsTechWantToWorkWith', 'NEWCollabToolsHaveWorkedWith',
       'NEWCollabToolsWantToWorkWith', 'OpSysProfessional use',
       'OpSysPersonal use', 'VersionControlSystem', 'VCInteraction',
       'VCHostingPersonal use', 'VCHostingProfessional use',
       'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith',
       'OfficeStackSyncHaveWorkedWith', 'OfficeStackSyncWantToWorkWith',
       'Blockchain', 'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq',
       'SOComm', 'Age', 'Gender', 'Trans', 'Sexuality', 'Ethnicity',
       'Accessibility', 'MentalHealth', 'TBranch', 'ICorPM', 'WorkExp',
       'Knowledge_1', 'Knowledge_2', 'Knowledge_3', 'Knowledge_4',
       'Knowledge_5', 'Knowledge_6', 'Knowledge_7', 'Frequency_1',
       'Frequency_2', 'Frequency_3', 'TimeSearching', 'TimeAnswering',
       'Onboarding', 'ProfessionalTech', 'TrueFalse_1', 'TrueFalse_2',
       'TrueFalse_3', 'SurveyLength', 'SurveyEase', 'ConvertedCompYearly'],
      dtype='object')

In [27]:
df["RemoteWork"]

0                                         NaN
1                                Fully remote
2        Hybrid (some remote, some in-person)
3                                Fully remote
4        Hybrid (some remote, some in-person)
                         ...
73263                            Fully remote
73264                          Full in-person
73265    Hybrid (some remote, some in-person)
73266    Hybrid (some remote, some in-person)
73267                            Fully remote
Name: RemoteWork, Length: 73268, dtype: object

In [28]:
df["RemoteWork"].value_counts()

Fully remote                            25341
Hybrid (some remote, some in-person)    25021
Full in-person                           8596
Name: RemoteWork, dtype: int64

In [29]:
df.loc[[0,1,2,3,4,5,6,7],"RemoteWork"]

0                                     NaN
1                            Fully remote
2    Hybrid (some remote, some in-person)
3                            Fully remote
4    Hybrid (some remote, some in-person)
5                                     NaN
6                                     NaN
7                                     NaN
Name: RemoteWork, dtype: object

In [30]:
df.loc[0:7,"RemoteWork"]

0                                     NaN
1                            Fully remote
2    Hybrid (some remote, some in-person)
3                            Fully remote
4    Hybrid (some remote, some in-person)
5                                     NaN
6                                     NaN
7                                     NaN
Name: RemoteWork, dtype: object

In [31]:
df.loc[0:7,"RemoteWork":"DevType"]

,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,5,Data scientist or machine learning specialist;...
3,Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,17,"Developer, full-stack"
4,"Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,3,"Developer, front-end;Developer, full-stack;Dev..."
5,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,15,NaN,NaN
6,NaN,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Stack Overflow;Video-based Online Courses,NaN,3,NaN,NaN
7,NaN,NaN,Some college/university study without earning ...,Online Courses or Certification,NaN,Coursera;Udemy,1,NaN,"Developer, full-stack;Student"

In [32]:
dict_df.set_index("email",inplace=True)

In [33]:
dict_df

                         first     last
email
CoreyMSchafer@gmail.com  Corey  Schafer
JaneDoe@email.com         Jane      Doe
JohnDoe@email.com         John      Doe

In [34]:
dict_df.index

Index(['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com'], dtype='object', name='email')

In [35]:
dict_df.loc["CoreyMSchafer@gmail.com"]

first      Corey
last     Schafer
Name: CoreyMSchafer@gmail.com, dtype: object

In [36]:
dict_df.reset_index(inplace=True)

In [37]:
schema_df.columns

Index(['qid', 'qname', 'question', 'force_resp', 'type', 'selector'], dtype='object')

In [38]:
schema_df

,qid,qname,question,force_resp,type,selector
0,QID16,S0,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
1,QID12,MetaInfo,Browser Meta Info,False,Meta,Browser
2,QID1,S1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
3,QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
4,QID296,Employment,Which of the following best describes your cur...,False,MC,MAVR
5,QID308,RemoteWork,Which best describes your current work situation?,False,MC,SAVR
6,QID297,CodingActivities,Which of the following best describes the code...,False,MC,MAVR
7,QID190,S2,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
8,QID25,EdLevel,Which of the following best describes the high...,False,MC,SAVR
9,QID276,LearnCode,How did you learn to code? Select all that apply.,False,MC,MAVR
10,QID281,LearnCodeOnline,What online resources do you use to learn to c...,False,MC,MAVR
11,QID306,LearnCodeCoursesCert,What online courses or certifications do you u...,False,MC,MAVR
12,QID32,YearsCode,"Including any education, how many years have y...",False,MC,DL
13,QID34,YearsCodePro,"NOT including education, how many years have y...",False,MC,DL
14,QID31,DevType,Which of the following describes your current ...,False,MC,MAVR
15,QID29,OrgSize,Approximately how many people are employed by ...,False,MC,MAVR
16,QID278,PurchaseInfluence,"What level of influence do you, personally, ha...",False,MC,SAVR
17,QID279,BuyNewTool,"When buying a new tool or software, how do you...",False,MC,MAVR
18,QID6,Country,"Where do you live? <span style=""font-weight: b...",True,MC,DL
19,QID50,Currency,Which currency do you use day-to-day? If your ...,True,MC,DL
20,QID51,CompTotal,What is your current total compensation (salar...,False,TE,SL
21,QID52,CompFreq,"Is that compensation weekly, monthly, or yearly?",False,MC,MAVR
22,QID61,S3,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
23,QID233,Language,"Which <b>programming, scripting, and markup la...",False,Matrix,Likert
24,QID262,Database,Which <b>database environments </b>have you do...,False,Matrix,Likert
25,QID263,Platform,Which <b>cloud platforms</b> have you done ext...,False,Matrix,Likert
26,QID264,Webframe,Which <b>web frameworks and web technologies</...,False,Matrix,Likert
27,QID265,MiscTech,Which <b>other frameworks and libraries</b> ha...,False,Matrix,Likert
28,QID275,ToolsTech,Which <b>developer </b><strong>tools</strong> ...,False,Matrix,Likert
29,QID274,NEWCollabTools,Which <strong>development environments</strong...,False,Matrix,Likert
30,QID71,OpSys,What is the primary <b>operating system</b> in...,False,Matrix,Likert
31,QID283,VersionControlSystem,What are the primary <b>version control system...,False,MC,MAVR
32,QID284,VCInteraction,How do you interact with your version control ...,False,MC,MAVR
33,QID285,VCHosting,What version control hosting service are you u...,False,Matrix,Likert
34,QID282,OfficeStackAsync,Which <b>collaborative work management tools</...,False,Matrix,Likert
35,QID307,OfficeStackSync,Which <b>communication tools</b> did you use r...,False,Matrix,Likert
36,QID305,Blockchain,"How favorable are you about blockchain, crypto...",False,MC,SAVR
37,QID91,S4,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
38,QID266,NEWSOSites,Which of the following Stack Overflow sites ha...,False,MC,MAVR
39,QID100,SOVisitFreq,How frequently would you say you visit Stack O...,False,MC,MAVR
40,QID101,SOAccount,Do you have a Stack Overflow account?,False,MC,MAVR
41,QID102,SOPartFreq,How frequently would you say you participate i...,False,MC,MAVR
42,QID106,SOComm,Do you consider yourself a member of the Stack...,False,MC,MAVR
43,QID121,S5,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
44,QID127,Age,What is your age?,False,MC,MAVR
45,QID122,Gender,"Which of the following describe you, if any? P...",False,MC,MAVR
46,QID153,Trans,Do you identify as transgender?,False,MC,MAVR
47,QID136,Sexuality,"Which of the following describe you, if any? P...",False,MC,MAVR
48,QID126,Ethnicity,"Which of the following describe you, if any? P...",False,MC,MAVR
49,QID124,Accessibility,"Which of the following describe you, if any? P...",False,MC,MAVR
50,QID125,MentalHealth,"Which of the following describe you, if any? P...",False,MC,MAVR
51,QID295,S6,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
52,QID299,TBranch,"<span style=""font-size:16px;"">Would you like t...",True,MC,SAVR
53,QID287,ICorPM,Are you an independent contributor or people m...,False,MC,SAVR
54,QID288,WorkExp,How many years of working experience do you have?,False,Slider,HSLIDER
55,QID289,Knowledge,Please rate your level of agreement with the f...,False,Matrix,Likert
56,QID290,Frequency,How frequently do you experience each of the f...,False,Matrix,Likert
57,QID291,TimeSearching,"On an average day, how much time do you typica...",False,MC,SAVR
58,QID292,TimeAnswering,"On an average day, how much time do you typica...",False,MC,SAVR
59,QID293,Onboarding,The time it takes to onboard new hires at my c...,False,MC,SAVR
60,QID304,ProfessionalTech,My company has:,False,MC,MAVR
61,QID286,SOTeamsUsage,Does your team use Stack Overflow for Teams?,False,MC,SAVR
62,QID294,TrueFalse,Last few questions...,False,Matrix,Likert
63,QID131,S7,"<span style=""font-size:22px;""><strong>Final Qu...",False,DB,TB
64,QID132,SurveyLength,How do you feel about the length of the survey...,False,MC,MAVR
65,QID133,SurveyEase,How easy or difficult was this survey to compl...,False,MC,MAVR
66,QID289,Knowledge_1,I have interactions with people outside of my ...,NaN,MC,MAVR
67,QID289,Knowledge_2,Knowledge silos prevent me from getting ideas ...,NaN,MC,MAVR
68,QID289,Knowledge_3,I can find up-to-date information within my or...,NaN,MC,MAVR
69,QID289,Knowledge_4,I am able to quickly find answers to my questi...,NaN,MC,MAVR
70,QID289,Knowledge_5,I know which system or resource to use to find...,NaN,MC,MAVR
71,QID289,Knowledge_6,I often find myself answering questions that I...,NaN,MC,MAVR
72,QID289,Knowledge_7,Waiting on answers to questions often causes i...,NaN,MC,MAVR
73,QID290,Frequency_1,Needing help from people outside of your immed...,NaN,MC,MAVR
74,QID290,Frequency_2,Interacting with people outside of your immedi...,NaN,MC,MAVR
75,QID290,Frequency_3,Encountering knowledge silos (where one indivi...,NaN,MC,MAVR
76,QID294,TrueFalse_1,Are you involved in supporting new hires durin...,NaN,MC,MAVR
77,QID294,TrueFalse_2,Do you use learning resources provided by your...,NaN,MC,MAVR
78,QID294,TrueFalse_3,Does your employer give you time to learn new ...,NaN,MC,MAVR

### Filtering the Data

In [39]:
df.head()

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Canada,CAD\tCanadian dollar,NaN,NaN,JavaScript;TypeScript,Rust;TypeScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,macOS,Windows Subsystem for Linux (WSL),Git,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,Daily or almost daily,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
2,3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,5,Data scientist or machine learning specialist;...,20 to 99 employees,I have some influence,NaN,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,32000.0,Yearly,C#;C++;HTML/CSS;JavaScript;Python,C#;C++;HTML/CSS;JavaScript;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,Angular.js,Angular;Angular.js,Pandas,.NET,NaN,NaN,Notepad++;Visual Studio,Notepad++;Visual Studio,Windows,Windows,Git,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Very unfavorable,Collectives on Stack Overflow;Stack Overflow;S...,Multiple times per day,Yes,Multiple times per day,Neutral,25-34 years old,Man,No,Bisexual,White,None of the above,"I have a mood or emotional disorder (e.g., dep...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
3,4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,17,"Developer, full-stack",100 to 499 employees,I have some influence,Other (please specify):,Israel,ILS\tIsraeli new shekel,60000.0,Monthly,C#;JavaScript;SQL;TypeScript,C#;SQL;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,.NET,.NET,NaN,NaN,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Jira Work Management;Trello,Jira Work Management;Trello,Slack;Zoom,Slack;Zoom,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,A few times per week,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
4,5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,3,"Developer, front-end;Developer, full-stack;Dev...",20 to 99 employees,I have some influence,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,NaN,NaN,C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,C#;Elixir;F#;Go;JavaScript;Rust;TypeScript,Cloud Firestore;Elasticsearch;Microsoft SQL Se...,Cloud Firestore;Elasticsearch;Firebase Realtim...,Firebase;Microsoft Azure,Firebase;Microsoft Azure,Angular;ASP.NET;ASP.NET Core ;jQuery;Node.js,Angular;ASP.NET Core ;Blazor;Node.js,.NET,.NET;Apache Kafka,npm,Docker;Kubernetes,Notepad++;Visual Studio;Visual Studio Code;Xcode,Rider;Visual Studio;Visual Studio Code,Windows,macOS;Windows,Git;Other (please specify):,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,NaN,Unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",25-34 years old,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN

In [40]:
high_salary=(df["CompTotal"]>70000)

In [41]:
high_salary

0        False
1        False
2        False
3        False
4        False
         ...
73263    False
73264     True
73265    False
73266    False
73267    False
Name: CompTotal, Length: 73268, dtype: bool

In [42]:
df.loc[high_salary,"WebframeWantToWorkWith"]

11       ASP.NET Core ;Node.js;Nuxt.js;React.js;Vue.js
14                      Django;FastAPI;React.js;Vue.js
17                                                 NaN
22                                       ASP.NET Core
25                                     Express;Node.js
                             ...
73246                                 Node.js;React.js
73253                                              NaN
73254                                              NaN
73258                                              NaN
73264                                 FastAPI;React.js
Name: WebframeWantToWorkWith, Length: 20183, dtype: object

In [43]:
countries=["India","United States"]

In [44]:
country_filt=df["Country"].isin(countries)

In [45]:
country_filt

0        False
1        False
2        False
3        False
4        False
         ...
73263    False
73264    False
73265    False
73266    False
73267    False
Name: Country, Length: 73268, dtype: bool

In [46]:
df.loc[country_filt]

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
6,7,I code primarily as a hobby,"Student, part-time",NaN,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Stack Overflow;Video-based Online Courses,NaN,3,NaN,NaN,NaN,NaN,Start a free trial;Visit developer communities...,India,NaN,NaN,NaN,C++;HTML/CSS;JavaScript;PHP;Python;TypeScript,C;C#;C++;Elixir;Go;HTML/CSS;Java;JavaScript;Ko...,Cloud Firestore;MongoDB;Firebase Realtime Data...,MySQL;Oracle;PostgreSQL,NaN,NaN,Angular;Next.js;Node.js;React.js;Svelte;Vue.js,Django;Flask;Gatsby;jQuery;Next.js;Node.js;Rea...,NaN,NaN,Homebrew;npm,npm,Atom;IntelliJ;Notepad++;PyCharm;Sublime Text;V...,Visual Studio Code;Webstorm,macOS,macOS,Git,Code editor;Command-line,NaN,NaN,NaN,NaN,Google Chat;Microsoft Teams;Slack;Zoom,Google Chat;Slack;Zoom,Favorable,Stack Overflow,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",Under 18 years old,Man,No,NaN,Indian,None of the above,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
7,8,I am a developer by profession,"Not employed, but looking for work",NaN,NaN,Some college/university study without earning ...,Online Courses or Certification,NaN,Coursera;Udemy,1,NaN,"Developer, full-stack;Student",NaN,NaN,Start a free trial,India,NaN,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;SQL,APL;Bash/Shell;Go;Python;TypeScript,MongoDB;MySQL,Neo4j;PostgreSQL,AWS;Google Cloud;Heroku,DigitalOcean;Firebase;Microsoft Azure;VMware,jQuery;Node.js,Angular;Angular.js;Next.js;Vue.js,NaN,NaN,npm,Unity 3D;Yarn,Atom;CLion;Eclipse;IntelliJ;Notepad++;Visual S...,Android Studio;IPython/Jupyter;Sublime Text;Vi...,Linux-based;macOS,Windows,Git,Command-line,NaN,NaN,NaN,NaN,Google Chat;Microsoft Teams;Zoom,NaN,Very favorable,Collectives on Stack Overflow;Stack Overflow;S...,A few times per week,Yes,I have never participated in Q&A on Stack Over...,"Yes, definitely",18-24 years old,Man,No,Straight / Heterosexual,Indian,None of the above,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN
65,66,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Other (please specify):,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Stack Overflow;Video-based Online Courses;Inte...,Udemy,3,2,"Developer, back-end;DevOps specialist","10,000 or more employees",I have little or no influence,Start a free trial;Visit developer communities...,India,INR\tIndian rupee,NaN,Monthly,C#,C++;JavaScript,MongoDB;MySQL,NaN,NaN,NaN,NaN,NaN,.NET,.NET;React Native;TensorFlow,NaN,NaN,Eclipse;Notepad++;Sublime Text;Visual Studio;V...,Notepad++;Visual Studio;Visual Studio Code,Windows,Linux-based,Git,Code editor;Command-line,NaN,NaN,Jira Work Management,Jira Work Management,Cisco Webex Teams;Microsoft Teams;Zoom,Microsoft Teams,Unfavorable,Stack Overflow;Stack Exchange,Daily or almost daily,Not sure/can't remember,NaN,"Yes, somewhat",18-24 years old,Man,No,Straight / Heterosexual,Indian,None of the above,None of the above,Yes,Independent contributor,2.0,Strongly agree,Agree,Disagree,Agree,Agree,Agree,Agree,Never,1-2 times a week,3-5 times a week,30-60 minutes a day,15-30 minutes a day,Just right,Microservices;Continuous integration (CI) and ...,No,Yes,Yes,Too long,Easy,NaN
140,141,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Written Tutorials;Stac...,NaN,13,12,"Developer, front-end;Developer, full-stack;Des...","10,000 or more employees",I have a great deal of influence,Start a free trial;Visit developer communities...,India,INR\tIndian rupee,NaN,NaN,HTML/CSS;JavaScript;Kotlin;TypeScript,Groovy,Elasticsearch;PostgreSQL,MongoDB,NaN,NaN,Angular;Express;jQuery,React.js;Vue.js,Spring,React Native,Kubernetes;npm,Docker;Puppet,IntelliJ,Visual Studio Code;Webstorm,Windows,Windows,Git,Code editor,NaN,NaN,Confluence;Trello,Jira Work Management;Stack Overflow for Teams,Microsoft Teams;Symphony,Cisco Webex Teams,Indifferent,Stack Overflow,Daily or almost daily,Not sure/can't remember,NaN,"Yes, definitely",25-34 years old,Man,No,Straight / Heterosexual,Indian,None of the above,None of the above,Yes,Independent contributor,12.0,Agree,Disagree,Agree,Agree,Neither agree nor disagree,Agree,Agree,Never,1-2 times a week,Never,30-60 minutes a day,30-60 minutes a day,Just right,DevOps function;Microservices;Developer portal...,Yes,Yes,Yes,Appropriate in length,Neither easy nor difficult,NaN
151,152,I am a developer by profession,"Employed, full-time",Full in-person,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;W...,Udemy;Pluralsight;Udacity,12,12,"Developer, full-stack;Data or business analyst","10,000 or more employees",I have some influence,Ask developers I know/work with;Research compa...,India,INR\tIndian rupee,100000.0,Monthly,Bash/Shell;HTML/CSS;Java;JavaScript;Python;SQL,Bash/Shell;HTML/CSS;Java;JavaScript;Python;SQL,Oracle;PostgreSQL;Redis;SQLite,Oracle;PostgreSQL;Redis;SQLite,Oracle Cloud Infrastructure,Oracle Cloud Infrastructure,Angular;Express;Flask;Next.js;Node.js;React.js,Angular;Express;Flask;Next.js;Node.js;React.js,NumPy;Pandas;Spring,NumPy;Pandas;Spring,Docker;Kubernetes;npm;Yarn,Docker;Kubernetes;npm;Yarn,Notepad++;Visual Studio Code,Notepad++;Visual Studio Code,Linux-based;Windows,Linux-based;Windows,Git;SVN,Command-line;Version control hosting service w...,NaN,NaN,Microsoft Lists,Microsoft Lists,Microsoft Teams,Microsoft Teams,Very favorable,Stack Overflow,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,Neutral,25-34 years old,Man,No,Straight / Heterosexual,Indian;Asian,None of the above,None of the above,Yes,People manager,12.0,Strongly agree,Disagree,Agree,Agree,Agree,Agree,Agree,Never,Never,Never,30-60 minutes a day,Less than 15 minutes a day,Somewhat long,None of these,Yes,Yes,Yes,Appropriate in length,Neither easy nor difficult,15480.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73184,73185,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Online Courses or Certification,NaN,edX,8,5,"Developer, full-stack","5,000 to 9,999 employees",I have some influence,Start a free trial;Visit developer communities...,India,INR\tIndian rupee,2000000.0,Yearly,Java;Python,Julia;Python,PostgreSQL;SQLite,MongoDB;PostgreSQL;SQLite,AWS,AWS;OpenStack,NaN,NaN,Apache Kafka;Spring,Apache Kafka;Apache Spark;Pandas;React Native,npm,npm,IntelliJ;PyCharm;Sublime Text;Vim;Webstorm,IntelliJ;PyCharm;Vim;Webstorm,Windows,Linux-based;Windows,Git;Other (please specify):,Code editor;Command-line,NaN,NaN,Confluence;Jira Work Management,Confluence;Jira Work Management,Microsoft Teams,Zoom,Favorable,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Daily or almost daily,"Yes, definitely",25-34 years old,Man,No,Straight / Heterosexual,Indian;Asian,None of the above,None of the above,Yes,Independent contributor,5.0,Strongly agree,Neither agree nor disagree,Agree,Agree,Agree,Agree,Agree,1-2 times a week,1-2 times a week,1-2 times a week,Over 120 minutes a day,30-60 minutes a day,Just right,Innersource initiative;DevOps function;Microse...,No,Yes,No,Appropriate in length,Easy,NaN
73193,73194,"I used to be a developer by profession, but no...","Employed, full-time",Fully remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Video-b...,Coursera;Udemy,20,18,"Senior Executive (C-Suite, VP, etc.)",NaN,NaN,Start a free trial;Ask developers I know/work ...,India,NaN,NaN,NaN,HTML/CSS;JavaScript,Go;HTML/CSS;Java;JavaScript;TypeScript,MongoDB;Firebase Realtime Database,MongoDB;PostgreSQL;Redis,AWS,AWS;Microsoft Azure,Angular.js;Express;Node.js;React.js,React.js,React Native,Apache Kafka;Flutter;React Native;Spring,Docker;Kubernetes,Docker;Kubernetes;Terraform;Yarn,Sublime Text;Vim;Visual Studio Code,Eclipse;Sublime Text;Vim;Visual Studio Code,macOS,macOS,Git,Command-line,NaN,NaN,Confluence;Jira Work Management,Confluence;Jira Work Management,Slack;Zoom,Slack;Zoom,Indifferent,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,Less than once per month or monthly,"Yes, somewhat",35-44 years old,Man,No,Straight / Heterosexual,Indian,None of the above,None of the above,Yes,People manager,18.0,Strongly agree,Agree,Agree,Agree,Agree,Disagree,Disagree,1-2 times a week,1-2 times a week,1-2 times a week,15-30 minutes a day,15-30 minutes a day,Somewhat long,DevOps function;Microservices;Developer portal...,Yes,Yes,Yes,Appropriate in length,Easy,NaN
73255,73256,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,14,7,"Developer, full-stack",100 to 499 employees,I have little or no influence,NaN,India,INR\tIndian rupee,NaN,Monthly,Bash/Shell;C#;HTML/CSS;JavaScript;Perl;PowerSh...,Bash/Shell;C#;HTML/CSS;JavaScript;Perl;PowerSh...,Microsoft SQL Server;MongoDB,Microsoft SQL Server;MongoDB,NaN,NaN,Angular;ASP.NET Core,Angular;ASP.NET Core ;React.js,.NET,.NET,Docker;Kubernetes;npm,Docker;Kubernetes;npm,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows,Windows,Git,Command-line;Version control hosting service w...,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Favorable,Collectives on Stack Overflow;Stack Overflow;S...,Daily or almost daily,Yes,Less than once per month or monthly,"Yes, somewhat",25-34 years old,Man,No,Prefer not to say,Indian,None of the above,None of the above,Yes,Independent contributor,7.0,Neither agree nor disagree,Agree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,1-2 times a week,1-2 times a week,1-2 times a week,60-120 minutes a day,Less than 15 minutes a day,Somewhat long,DevOps function;Microservices;Continuous integ...,Yes,Yes,Yes,Too long,Neither easy nor difficult,NaN
73257,73258,I am learning to code,"Student, full-time",NaN,NaN,"Secondary school (e.g. American high school, G...",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,NaN,7,NaN,NaN,NaN,NaN,Visit developer communities like Stack Overflo...,India,NaN,NaN,NaN,C;Python;SQL,C;C++,MySQL,NaN,NaN,NaN,NaN,NaN,.NET,NaN,NaN,NaN,Visual Studio;Visual Studio Code,Visual Studio Code,NaN,Windows,Git,Command-line,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,NaN,Very unfavorable,Stack Overflow;Stack Exchange,Less than once per month or monthly,Yes,Less than once per month or monthly,"No, not at all",Under 18 years old,Man,No,Straight / Heterosexual,Indian,None of the above,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN
73258,73259,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Stack Overflow;Video-based Online Courses;Onli...,Coursera;Udemy,5,1,"Developer, back-end",100 to 499 employees,I have some influence,Start a free trial;Ask developers I know/work ...,India,INR\tIndian rupee,3200000.0,Yearly,Go;Java;SQL,JavaScript;TypeScript,MongoDB;MySQL,MySQL;Redis,AWS,Google Cloud,NaN,NaN,Apache Kafka;Spring,NaN,Docker;Homebrew;Kubernetes;npm,Kubernetes,Eclipse;GoLand;Vim;Visual Studio Code,GoLand;Vim;Visual Studio Code,macOS,Linux-based;Windows,Git,Command-line,NaN,NaN,Notion,NaN,Slack;Zoom,NaN,Very favorable,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Less than once per month or monthly,"Yes, somewhat",18-24 years old,Man,No,Straight / Heterosexual,Asian,NaN,None of the above,Yes,Independent contributor,1.0,Strongly agree,Disagree,Strongly agree,Agree,Neither agree nor disagree,Agree,Agree,1-2 times a week,10+ times a week,Never,15-30 minutes a day,15-30 minutes a day,Just right,DevOps function;Microservices;Developer portal...,Yes,Yes,Yes,Too long,Neither easy nor difficult,NaN

In [47]:
df["LanguageHaveWorkedWith"]

0                                                      NaN
1                                    JavaScript;TypeScript
2                        C#;C++;HTML/CSS;JavaScript;Python
3                             C#;JavaScript;SQL;TypeScript
4              C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript
                               ...
73263    Bash/Shell;Dart;JavaScript;PHP;Python;SQL;Type...
73264            Bash/Shell;HTML/CSS;JavaScript;Python;SQL
73265                   HTML/CSS;JavaScript;PHP;Python;SQL
73266                                        C#;Delphi;VBA
73267          C#;JavaScript;Lua;PowerShell;SQL;TypeScript
Name: LanguageHaveWorkedWith, Length: 73268, dtype: object

In [48]:
languages_filt=df["LanguageHaveWorkedWith"].str.contains("Python",na=False)

In [49]:
languages_filt

0        False
1        False
2         True
3        False
4        False
         ...
73263     True
73264     True
73265     True
73266    False
73267    False
Name: LanguageHaveWorkedWith, Length: 73268, dtype: bool

In [50]:
df.loc[languages_filt,"LanguageHaveWorkedWith"]

2                        C#;C++;HTML/CSS;JavaScript;Python
6            C++;HTML/CSS;JavaScript;PHP;Python;TypeScript
11       C#;HTML/CSS;JavaScript;PowerShell;Python;Rust;SQL
14             HTML/CSS;JavaScript;PHP;Python;R;Ruby;Scala
16                                    C#;Java;PHP;Python;R
                               ...
73257                                         C;Python;SQL
73261    Bash/Shell;HTML/CSS;Java;JavaScript;Python;SQL...
73263    Bash/Shell;Dart;JavaScript;PHP;Python;SQL;Type...
73264            Bash/Shell;HTML/CSS;JavaScript;Python;SQL
73265                   HTML/CSS;JavaScript;PHP;Python;SQL
Name: LanguageHaveWorkedWith, Length: 34155, dtype: object

### Adding and deleting rows operation in pandas dataframe

In [51]:
people2 = {
    "first": ["Steve", 'Tony', 'Peter'], 
    "last": ["Rogers", 'Stark', 'Parker'], 
    "email": ["capamerica@gmail.com", 'ironman@email.com', 'spiderman@email.com']
}

In [52]:
dict_df2=pd.DataFrame(people2)

In [53]:
dict_df2

   first    last                 email
0  Steve  Rogers  capamerica@gmail.com
1   Tony   Stark     ironman@email.com
2  Peter  Parker   spiderman@email.com

In [54]:
dict_df=dict_df.append(dict_df2,ignore_index=True,sort=False)

In [55]:
dict_df

                     email  first     last
0  CoreyMSchafer@gmail.com  Corey  Schafer
1        JaneDoe@email.com   Jane      Doe
2        JohnDoe@email.com   John      Doe
3     capamerica@gmail.com  Steve   Rogers
4        ironman@email.com   Tony    Stark
5      spiderman@email.com  Peter   Parker

### Sorting

In [56]:
dict_df.sort_values(by="last")

                     email  first     last
1        JaneDoe@email.com   Jane      Doe
2        JohnDoe@email.com   John      Doe
5      spiderman@email.com  Peter   Parker
3     capamerica@gmail.com  Steve   Rogers
0  CoreyMSchafer@gmail.com  Corey  Schafer
4        ironman@email.com   Tony    Stark

In [57]:
dict_df.sort_index()

                     email  first     last
0  CoreyMSchafer@gmail.com  Corey  Schafer
1        JaneDoe@email.com   Jane      Doe
2        JohnDoe@email.com   John      Doe
3     capamerica@gmail.com  Steve   Rogers
4        ironman@email.com   Tony    Stark
5      spiderman@email.com  Peter   Parker

In [61]:
df.head(5)

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Canada,CAD\tCanadian dollar,NaN,NaN,JavaScript;TypeScript,Rust;TypeScript,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,macOS,Windows Subsystem for Linux (WSL),Git,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,Daily or almost daily,Not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
2,3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,5,Data scientist or machine learning specialist;...,20 to 99 employees,I have some influence,NaN,United Kingdom of Great Britain and Northern I...,GBP\tPound sterling,32000.0,Yearly,C#;C++;HTML/CSS;JavaScript;Python,C#;C++;HTML/CSS;JavaScript;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,Angular.js,Angular;Angular.js,Pandas,.NET,NaN,NaN,Notepad++;Visual Studio,Notepad++;Visual Studio,Windows,Windows,Git,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Very unfavorable,Collectives on Stack Overflow;Stack Overflow;S...,Multiple times per day,Yes,Multiple times per day,Neutral,25-34 years old,Man,No,Bisexual,White,None of the above,"I have a mood or emotional disorder (e.g., dep...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
3,4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,17,"Developer, full-stack",100 to 499 employees,I have some influence,Other (please specify):,Israel,ILS\tIsraeli new shekel,60000.0,Monthly,C#;JavaScript;SQL;TypeScript,C#;SQL;TypeScript,Microsoft SQL Server,Microsoft SQL Server,NaN,NaN,ASP.NET;ASP.NET Core,ASP.NET;ASP.NET Core,.NET,.NET,NaN,NaN,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Jira Work Management;Trello,Jira Work Management;Trello,Slack;Zoom,Slack;Zoom,Very unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,A few times per week,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,White,None of the above,None of the above,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
4,5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,3,"Developer, front-end;Developer, full-stack;Dev...",20 to 99 employees,I have some influence,Start a free trial;Visit developer communities...,United States of America,USD\tUnited States dollar,NaN,NaN,C#;HTML/CSS;JavaScript;SQL;Swift;TypeScript,C#;Elixir;F#;Go;JavaScript;Rust;TypeScript,Cloud Firestore;Elasticsearch;Microsoft SQL Se...,Cloud Firestore;Elasticsearch;Firebase Realtim...,Firebase;Microsoft Azure,Firebase;Microsoft Azure,Angular;ASP.NET;ASP.NET Core ;jQuery;Node.js,Angular;ASP.NET Core ;Blazor;Node.js,.NET,.NET;Apache Kafka,npm,Docker;Kubernetes,Notepad++;Visual Studio;Visual Studio Code;Xcode,Rider;Visual Studio;Visual Studio Code,Windows,macOS;Windows,Git;Other (please specify):,Code editor,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,NaN,Unfavorable,Collectives on Stack Overflow;Stack Overflow f...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",25-34 years old,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN

In [63]:
df[["Country","CompTotal"]].head(50)

                                              Country  CompTotal
0                                                 NaN        NaN
1                                              Canada        NaN
2   United Kingdom of Great Britain and Northern I...    32000.0
3                                              Israel    60000.0
4                            United States of America        NaN
5                                             Germany        NaN
6                                               India        NaN
7                                               India        NaN
8                                         Netherlands    46000.0
9                                             Croatia        NaN
10  United Kingdom of Great Britain and Northern I...    48000.0
11                           United States of America   194400.0
12                           United States of America    65000.0
13                                          Australia        NaN
14                           United States of America   110000.0
15                                 Russian Federation        NaN
16                                     Czech Republic    37000.0
17                                            Austria   190000.0
18                                            Austria     4000.0
19                                             Serbia        NaN
20                                            Austria        NaN
21                                              Italy    32000.0
22                                             Canada   125000.0
23                                        Netherlands        NaN
24                                             Israel        NaN
25                                            Germany    85000.0
26                           United States of America   106960.0
27                                             Israel        NaN
28                           United States of America   130000.0
29                                            Ireland   130000.0
30                                                NaN        NaN
31                           United States of America   102000.0
32                                             Canada        NaN
33                                             Israel        NaN
34                                             Poland    30000.0
35                                             Israel        NaN
36                                             Canada        NaN
37                                             Israel        NaN
38                                           Slovenia        NaN
39                                     Czech Republic        NaN
40                           United States of America   130000.0
41                                             Israel    19000.0
42                                               Iraq        NaN
43                                             Sweden        NaN
44                                            Austria        NaN
45                                         Madagascar      400.0
46                                             Norway        NaN
47                           United States of America   135000.0
48                                            Germany   100000.0
49                                            Germany     4000.0

In [65]:
df.sort_values(by=["Country","CompTotal"],ascending=[True,False],inplace=True)

In [66]:
df

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
6891,6892,I am a developer by profession,"Employed, full-time",Full in-person,Contribute to open-source projects;Freelance/c...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,Coursera;Udemy,3,1,"Developer, full-stack;Developer, back-end;Deve...",10 to 19 employees,I have some influence,Start a free trial;Ask developers I know/work ...,Afghanistan,IRR\tIranian rial,55000000.0,Monthly,HTML/CSS;JavaScript,Go;HTML/CSS;JavaScript;TypeScript,MongoDB;MySQL,Elasticsearch;MongoDB;MySQL;Redis,Heroku;Managed Hosting,Heroku;Managed Hosting,Next.js;Node.js;React.js,Deno;Django;FastAPI;Vue.js,NaN,NaN,npm;Yarn,Docker;Kubernetes;Yarn,Visual Studio Code;Webstorm,Visual Studio Code;Webstorm,Linux-based;Windows,Windows,Git,Command-line,NaN,NaN,Trello,NaN,NaN,NaN,Favorable,Stack Overflow,Multiple times per day,Yes,A few times per month or weekly,"Yes, somewhat",18-24 years old,Man,No,Straight / Heterosexual,Asian,None of the above,"I have a mood or emotional disorder (e.g., dep...",Yes,Independent contributor,2.0,Neither agree nor disagree,Neither agree nor disagree,Disagree,Agree,Agree,Strongly agree,Neither agree nor disagree,1-2 times a week,1-2 times a week,1-2 times a week,Over 120 minutes a day,Less than 15 minutes a day,Somewhat long,None of these,Yes,Yes,Yes,Too long,Easy,15600.0
38512,38513,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects;Boots...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,Coursera;Udemy;Udacity;Skillsoft,40,36,Data scientist or machine learning specialist;...,"10,000 or more employees",I have a great deal of influence,Ask developers I know/work with;Research compa...,Afghanistan,AFN\tAfghan afghani,1200000.0,Monthly,APL;Assembly;Bash/Shell;C;C#;C++;COBOL;Crystal...,NaN,IBM DB2;Microsoft SQL Server;MySQL;Oracle;Post...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Linux-based;Windows,Linux-based;Windows,SVN,Dedicated version control GUI application,NaN,NaN,NaN,NaN,NaN,NaN,Very favorable,I have never visited Stack Overflow or the Sta...,NaN,Not sure/can't remember,NaN,Not sure,18-24 years old,"Non-binary, genderqueer, or gender non-conforming","Or, in your own words:",Bisexual;Straight / Heterosexual;Gay or Lesbia...,White;Indian;European;North American;Middle Ea...,I am deaf / hard of hearing;I am blind / have ...,"I have a mood or emotional disorder (e.g., dep...",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,158484.0
43639,43640,I am a developer by profession,"Employed, full-time;Independent contractor, fr...",Fully remote,Hobby;Bootstrapping a business,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,Pluralsight;Other,12,9,"Developer, back-end",500 to 999 employees,I have little or no influence,Start a free trial;Visit developer communities...,Afghanistan,AFN\tAfghan afghani,700000.0,Monthly,PHP,PHP,MySQL,MySQL,AWS;DigitalOcean,DigitalOcean,jQuery;Symfony,jQuery;Symfony,NaN,NaN,Docker;npm;Yarn,Docker;npm;Yarn,Notepad++;PhpStorm,Notepad++;PhpStorm,Linux-based,Linux-based,Git,Command-line,NaN,NaN,Confluence;Jira Work Management,Confluence;Jira Work Management,Slack,Slack,Unsure,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,A few times per month or weekly,"Yes, somewhat",25-34 years old,Man,No,Straight / Heterosexual,Asian;Central Asian,None of the above,I have an anxiety disorder,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,92448.0
43690,43691,I am a developer by profession,"Employed, full-time;Independent contractor, fr...","Hybrid (some remote, some in-person)",Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,Udemy;Codecademy;edX;Other,8,5,"Developer, full-stack;Product manager",500 to 999 employees,I have little or no influence,Start a free trial;Visit developer communities...,Afghanistan,AFN\tAfghan afghani,100000.0,Monthly,C++;HTML/CSS;JavaScript;PHP;TypeScript,C++;HTML/CSS;JavaScript;Python;Rust;TypeScript,Cloud Firestore;MongoDB;MySQL;PostgreSQL;SQLite,Cloud Firestore;MongoDB;MySQL;PostgreSQL;Redis...,AWS;DigitalOcean;Firebase,AWS;DigitalOcean;Firebase,Express;Gatsby;jQuery;Laravel;Next.js;Node.js;...,Express;Laravel;Next.js;Node.js;Nuxt.js;React....,NaN,NaN,Docker;Homebrew;npm;Yarn,Docker;Homebrew;npm;Unity 3D;Yarn,Sublime Text;Visual Studio Code,Sublime Text;Visual Studio Code,Linux-based;macOS,macOS,Git,Code editor;Command-line,NaN,NaN,Confluence;Jira Work Management,Confluence;Jira Work Management,Slack;Zoom,Slack;Zoom,Very favorable,Collectives on Stack Overflow;Stack Overflow;S...,A few times per week,Yes,I have never participated in Q&A on Stack Over...,"Yes, definitely",25-34 years old,Man,No,Straight / Heterosexual,Asian;South Asian,None of the above,None of the above,Yes,Independent contributor,8.0,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,1-2 times a week,1-2 times a week,1-2 times a week,30-60 minutes a day,15-30 minutes a day,Just right,Microservices,Yes,Yes,Yes,Appropriate in length,Neither easy nor difficult,13212.0
2448,2449,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects;Schoo...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,15,10,"Developer, full-stack;Developer, back-end;Deve...",100 to 499 employees,I have some influence,Ask developers I know/work with,Afghanistan,AED United Arab Emirates dirham,40000.0,Yearly,Bash/Shell;C;C++;HTML/CSS;Java;JavaScript;Kotl...,Bash/Shell;C;Java;Kotlin;Objective-C;Python;Rust,Cassandra;CouchDB;Cloud Firestore;DynamoDB;Mar...,Cloud Firestore;MariaDB,AWS;Firebase;Google Cloud;Heroku;OpenStack;VMware,OpenStack,Angular;Django;Express;Flask;Gatsby;Next.js;No...,Flask;Next.js;Node.js,.NET;Apache Kafka;Capacitor;Flutter;Spring;Ten...,TensorFlow,Ansible;Chef;Docker;Homebrew;Kubernetes;npm,Docker;Kubernetes,Android Studio;Neovim;Visual Studio Code;Xcode,Android Studio;Neovim;Xcode,macOS,BSD;Linux-based,Git,Command-line,NaN,NaN,Confluence;Jira Work Management,Confluence;Jira Work Management,Google Chat;Microsoft Teams;Zoom,Google Chat,Very unfavorable,Stack Overflow;Stack Exchange,A few times per week,Not sure/can't remember,NaN,Neutral,NaN,"Or, in your own words:","Or, in your own words:",Prefer to self-describe:,"Or, in your own words:",None of the above,"I have a mood or emotional disorder (e.g., dep...",Yes,Independent contributor,15.0,Strongly agree,Strongly disagree,Strongly agree,Strongly agree,Strongly agree,Agree,Agree,Never,1-2 times a week,1-2 times a week,15-30 minutes a day,30-60 minutes a day,Very short,DevOps function;Continuous integration (CI) an...,Yes,Yes,Yes,Too long,Easy,10894.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73109,73110,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73157,73158,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73201,73202,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73215,73216,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73243,73244,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
df[["Country","CompTotal"]].head(50)

           Country   CompTotal
6891   Afghanistan  55000000.0
38512  Afghanistan   1200000.0
43639  Afghanistan    700000.0
43690  Afghanistan    100000.0
2448   Afghanistan     40000.0
6242   Afghanistan     40000.0
23223  Afghanistan     40000.0
49273  Afghanistan      6000.0
55665  Afghanistan       200.0
3886   Afghanistan         1.0
5464   Afghanistan         1.0
6776   Afghanistan         1.0
17469  Afghanistan         1.0
2737   Afghanistan         0.0
67666  Afghanistan         0.0
1959   Afghanistan         NaN
3641   Afghanistan         NaN
3775   Afghanistan         NaN
4502   Afghanistan         NaN
7944   Afghanistan         NaN
8890   Afghanistan         NaN
10233  Afghanistan         NaN
10910  Afghanistan         NaN
13851  Afghanistan         NaN
15607  Afghanistan         NaN
17038  Afghanistan         NaN
19201  Afghanistan         NaN
21765  Afghanistan         NaN
22876  Afghanistan         NaN
23161  Afghanistan         NaN
24812  Afghanistan         NaN
25962  Afghanistan         NaN
26617  Afghanistan         NaN
28434  Afghanistan         NaN
28582  Afghanistan         NaN
29704  Afghanistan         NaN
30040  Afghanistan         NaN
30850  Afghanistan         NaN
32132  Afghanistan         NaN
33328  Afghanistan         NaN
33428  Afghanistan         NaN
34043  Afghanistan         NaN
42122  Afghanistan         NaN
42870  Afghanistan         NaN
46025  Afghanistan         NaN
46422  Afghanistan         NaN
48959  Afghanistan         NaN
51188  Afghanistan         NaN
51547  Afghanistan         NaN
53960  Afghanistan         NaN

In [68]:
 df["CompTotal"].nlargest(10)

35786    9.000000e+56
3068     1.000000e+52
70597    1.000000e+22
17567    1.000000e+15
19244    5.000000e+12
24640    1.500070e+12
31190    1.000000e+12
71603    9.363220e+09
34411    7.200000e+09
49874    6.438169e+09
Name: CompTotal, dtype: float64

In [69]:
df.nlargest(10,"CompTotal")

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
35786,35787,I am a developer by profession,"Employed, full-time;Employed, part-time","Hybrid (some remote, some in-person)",I don’t code outside of work,"Secondary school (e.g. American high school, G...",Colleague,NaN,NaN,4,16,"Developer, full-stack;Academic researcher","Just me - I am a freelancer, sole proprietor, ...",I have a great deal of influence,Visit developer communities like Stack Overflow,Ecuador,DOP\tDominican peso,9.000000e+56,Weekly,APL;COBOL;Scala,C++;Dart;MATLAB;VBA,IBM DB2,Neo4j;Redis,DigitalOcean,Heroku,Angular,Blazor;Svelte,Scikit-learn,Tidyverse,Puppet,Yarn,Android Studio,Android Studio,Windows,BSD,Other (please specify):;Mercurial,Command-line,NaN,NaN,Airtable,Planview Projectplace or Clarizen,Google Chat,RingCentral,Indifferent,Stack Overflow for Teams (private knowledge sh...,A few times per week,No,NaN,"No, not really",65 years or older,"Man;Woman;Non-binary, genderqueer, or gender n...",No,Straight / Heterosexual,White;Indian;European;North American;Middle Ea...,I am deaf / hard of hearing;I am blind / have ...,"I have a mood or emotional disorder (e.g., dep...",Yes,People manager,50.0,Disagree,Neither agree nor disagree,Agree,Strongly agree,Agree,Neither agree nor disagree,Disagree,10+ times a week,10+ times a week,10+ times a week,Over 120 minutes a day,Over 120 minutes a day,Just right,DevOps function;Automated testing,Yes,No,Yes,Too long,Difficult,NaN
3068,3069,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","School (i.e., University, College, etc);Other ...",NaN,NaN,10,2,"Developer, back-end;Scientist","10,000 or more employees",I have some influence,NaN,United States of America,USD\tUnited States dollar,1.000000e+52,Weekly,C;C++;Fortran;Java;Python;Scala,Python;Rust;Scala,Cassandra;PostgreSQL;Redis;SQLite,Cassandra;PostgreSQL;Redis;SQLite,AWS,NaN,Flask,Flask,Apache Kafka;Apache Spark,Apache Kafka;Apache Spark,Docker;Kubernetes,Docker;Kubernetes,IntelliJ;PyCharm;Vim,IntelliJ;PyCharm;Vim,Linux-based,Linux-based;Windows,Git,Command-line;Version control hosting service w...,NaN,NaN,Confluence,Confluence,Microsoft Teams;Rocketchat,Rocketchat,Unsure,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Less than once per month or monthly,"No, not at all",18-24 years old,Man,"Or, in your own words:",Prefer to self-describe:,"Or, in your own words:","Or, in your own words:","Or, in your own words:",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Difficult,NaN
70597,70598,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Fully remote,Hobby;Contribute to open-source projects,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,NaN,20,19,"Developer, front-end;Developer, full-stack;Dev...","Just me - I am a freelancer, sole proprietor, ...",I have a great deal of influence,Other (please specify):,United States of America,ZMW Zambian kwacha,1.000000e+22,Yearly,Bash/Shell;HTML/CSS;JavaScript;Perl;PHP;SQL,NaN,MariaDB;MySQL,NaN,NaN,NaN,jQuery,NaN,NaN,NaN,NaN,NaN,Nano,NaN,BSD;Linux-based,Linux-based,Git;SVN,Command-line,NaN,NaN,NaN,NaN,NaN,NaN,Unfavorable,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,"No, not really",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17567,17568,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Contribute to open-source projects;Freel...,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Online ...,NaN,10,6,"Developer, front-end;Developer, full-stack;Dev...",10 to 19 employees,I have some influence,Visit developer communities like Stack Overflo...,Italy,EUR European Euro,1.000000e+15,Monthly,HTML/CSS;JavaScript;PHP;SQL,C#;Go;HTML/CSS;Java;JavaScript;PHP;Python;R;SQ...,MariaDB;MongoDB;MySQL;SQLite,MariaDB;MongoDB;MySQL;SQLite,AWS;DigitalOcean;Managed Hosting,AWS;DigitalOcean;Google Cloud;Managed Hosting;...,Angular.js;jQuery;Laravel;Node.js;Vue.js,Angular;Angular.js;jQuery;Laravel;Node.js;Reac...,NaN,NaN,Docker;Homebrew;npm,Docker;Homebrew;npm,Nano;PhpStorm;Vim,Nano;PhpStorm;Vim,macOS,Linux-based;Windows,Git,Code editor;Command-line,NaN,NaN,Trello,NaN,Google Chat;Microsoft Teams;Slack;Zoom,Google Chat;Microsoft Teams;Slack;Zoom,Indifferent,Collectives on Stack Overflow;Stack Overflow;S...,Multiple times per day,Yes,A few times per week,"Yes, somewhat",25-34 years old,Man,No,Straight / Heterosexual,European,None of the above,None of the above,Yes,Independent contributor,8.0,Strongly agree,Neither agree nor disagree,Strongly agree,Strongly agree,Strongly agree,Neither agree nor disagree,Agree,Never,Never,Never,15-30 minutes a day,Less than 15 minutes a day,Somewhat short,DevOps function;Microservices;Continuous integ...,Yes,Yes,Yes,Too long,Neither easy nor difficult,NaN
19244,19245,"I am not primarily a developer, but I write co...","Independent contractor, freelancer, or self-em...",Fully remote,Hobby;Contribute to open-source projects;Freel...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Programming Games;Writ...,NaN,15,10,"Developer, front-end;Engineer, data;Developer,...",10 to 19 employees,I have little or no influence,Other (please specify):;Visit developer commun...,Kyrgyzstan,KGS\tKyrgyzstani som,5.000000e+12,Yearly,Bash/Shell;C++;Go;HTML/CSS;JavaScript;MATLAB;P...,Bash/Shell;HTML/CSS;JavaScript;PHP;SQL;TypeScript,Elasticsearch;MariaDB;MongoDB;MySQL;Oracle;Pos...,Elasticsearch;MariaDB;MySQL,DigitalOcean;Firebase;Google Cloud;Oracle Clou...,DigitalOcean;Firebase,Angular;Django;Drupal;Gatsby;jQuery;Laravel;No...,Angular;Vue.js,Apache Kafka;Apache Spark;React Native;Torch/P...,NaN,Docker,Ansible;Docker;Flow;Kubernetes;npm;Puppet;Unit...,Android Studio;Atom;IntelliJ;NetBeans;Neovim;N...,Atom;Notepad++;PhpStorm;PyCharm,Linux-based,BSD;Linux-based;Windows;Windows Subsystem for ...,Git,Code editor;Command-line;Version control hosti...,NaN,NaN,Microsoft Planner;Trello,NaN,Google Chat;Rocketchat;Slack;Symphony;Zoom,NaN,Favorable,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Daily or almost daily,"Yes, definitely",35-44 years old,"Man;Or, in your own words:","Or, in your own words:",Straight / Heterosexual;Prefer to self-describe:,White;Asian;Multiracial;Central Asian,"Or, in your own words:;I am deaf / hard of hea...","Or, in your own words:",No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
24640,24641,I am a developer by profession,"Employed, full-time",Full in-person,Hobby;Contribute to open-source projects;Boots...,"Secondary school (e.g. American high school, G...",Books / Physical media,NaN,NaN,2,NaN,Project manager,"Just me - I am a freelancer, sole proprietor, ...",I have a great deal of influence,Read ratings or reviews on third party sites l...,Nigeria,NGN\tNigerian naira,1.500070e+12,Weekly,HTML/CSS;JavaScript;PowerShell;TypeScript,NaN,Cloud Firestore;Microsoft SQL Server;Firebase ...,NaN,DigitalOcean;Google Cloud;Microsoft Azure;Open...,DigitalOcean;Google Cloud;Microsoft Azure;Open...,ASP.NET;Express,NaN,.NET;Flutter,NaN,Flow;Terraform,NaN,Eclipse;NetBeans;Notepad++;Qt Creator,NaN,NaN,Windows,I don't use one,NaN,NaN,NaN,Adobe Workfront;Microsoft Planner;Microsoft Lists,Stack Overflow for Teams,NaN,NaN,Unfavorable,Stack Overflow for Teams (private knowledge sh...,A few times per week,No,NaN,Neutral,18-24 years old,Man,No,Straight / Heterosexual;Queer,African;South American,None of the above,None of the above,Yes,Independent contributor,9.0,Disagree,Agree,Agree,Agree,Agree,Agree,Agree,1-2 times a week,NaN,NaN,Over 120 minutes a day,Less than 15 minutes a day,Somewhat short,DevOps function,Yes,Yes,Yes,Appropriate in length,Neither easy nor difficult,NaN
31190,31191,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",I don’t code outside of work,"Other doctoral degree (Ph.D., Ed.D., etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,Coursera;Udemy;Codecademy;Pluralsight;edX;Udac...,10,Less than 1 year,Data scientist or machine learning specialist;...,I don’t know,I have a great deal of influence,Other (please specify):;Start a free trial;Vis...,United States of America,USD\tUnited States dollar,1.000000e+12,Monthly,APL;Assembly;Bash/Shell;C;C#;C++;Clojure;COBOL...,APL;Assembly;Bash/Shell;C;C#;C++;Clojure;COBOL...,Cassandra;Couchbase;CouchDB;Cloud Firestore;Dy...,Cassandra;Couchbase;CouchDB;Cloud Firestore;Dy...,AWS;Colocation;DigitalOcean;Firebase;Google Cl...,AWS;Colocation;DigitalOcean;Firebase;Google Cl...,Angular;Angular.js;ASP.NET;ASP.NET Core ;Blazo...,Angular;Angular.js;ASP.NET;ASP.NET Core ;Blazo...,.NET;Apache Kafka;Apache Spark;Capacitor;Cordo...,.NET;Apache Kafka;Apache Spark;Capacitor;Cordo...,Ansible;Chef;Docker;Flow;Homebrew;Kubernetes;n...,Ansible;Chef;Docker;Flow;Homebrew;Kubernetes;n...,Atom;CLion;Eclipse;Emacs;GoLand;IntelliJ;IPyth...,Atom;CLion;Eclipse;Emacs;GoLand;IntelliJ;IPyth...,BSD;Linux-based;macOS;Windows;Windows Subsyste...,BSD;Linux-based;macOS;Windows;Windows Subsyste...,I don't use one,NaN,NaN,NaN,Adobe Workfront;Airtable;Asana;Cerri;ClickUp;C...,Adobe Workfront;Airtable;Asana;Cerri;ClickUp;C...,Cisco Webex Teams;Coolfire Core;Google Chat;Ma...,Cisco Webex Teams;Coolfire Core;Google Chat;Ma...,Very favorable,Collectives on Stack Overflow;Stack Overflow f...,Daily or almost daily,Yes,Daily or almost daily,NaN,25-34 years old,"Or, in your own words:",No,Straight / Heterosexual,White;Indian;European;North American;Middle Ea...,Prefer not to say,I have a concentration and/or memory disorder ...,Yes,People manager,15.0,Strongly agree,Strongly disagree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Strongly agree,Never,1-2 times a week,1-2 times a week,60-120 minutes a day,60-120 minutes a day,Very short,Innersource initiative;DevOps function;Microse...,Yes,Yes,Yes,Appropriate in length,Neither easy nor difficult,NaN
71603,71604,I am a developer by profession,"Employed, part-time",Fully remote,Hobby,Something else,Other (please specify):,NaN,NaN,4,NaN,Scientist,"Just me - I am a freelancer, sole proprietor, ...",I have little or no influence,Start a free trial,"Iran, Islamic Republic of...",USD\tUnited States dollar,9.363220e+09,Monthly,APL,NaN,Cassandra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other (please specify):,NaN,NaN,Command-line,NaN,NaN,NaN,NaN,Microsoft Teams,Google Chat;Microsoft Teams;Wickr,Unsure,Stack Exchange,Less than once per month or monthly,No,NaN,Neutral,35-44 years old,Prefer not to say,No,NaN,Asian,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Neither easy nor difficult,NaN
34411,34412,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Bootstrapping a business;Freelance/contract work,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Stack Overflow;V...,Udemy;Pluralsight;Udacity,16,12,"Developer, full-stack;Developer, desktop or en...",20 to 99 employees,I have some influence,Start a free trial;Visit developer communities...,"Iran, Islamic Republic of...",IRR\tIranian rial,7.200000e+09,Monthly,C;C#;JavaScript;PHP;SQL;TypeScript,C#;Dart;F#;Go;JavaScript;SQL;TypeScript,Microsoft SQL Server;MySQL;Oracle,Cassandra;Elasticsearch;Microsoft SQL Server;P...,NaN,NaN,Angular;Angular.js;ASP.NET;ASP.NET Core ;jQuer...,Angular;ASP.NET Core ;Node.js;Vue.js,.NET;Cordova;Ionic;React Native;Xamarin,.NET;Capacitor;Flutter;Ionic,npm;Yarn,Docker;Kubernetes;npm;Yarn,Visual Studio;Visual Studio Code,Visual Studio;Visual Studio Code,Windows,Windows,Git,Code editor;Command-line,NaN,NaN,Jira Work Management,Jira Work Management,Microsoft Teams,Microsoft Teams;Zoom,Favorable,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Less than once per month or monthly,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,Middle Eastern,None of the above,None of the above,Yes,People manager,16.0,Agree,Neither agree nor disagree,Agree,Agree,NaN,Agree,Neither agree nor disagree,1-2 times a week,1-2 times a week,Never,30-60 minutes a day,15-30 minutes a day,Somewhat long,DevOps function;Microservices;Continuous integ...,Yes,Yes,Yes,Appropriate in length,Easy,2042400.0
49874,49875,I am a developer by profession,"Employed, full-time",Fully remote,Contribute to open-source projects,Primary/elementary school,Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,Coursera;Udemy;Codecademy;Pluralsight;edX;Udac...,19,10,Data scientist or machine learning specialist;...,"1,000 to 4,999 employees",I have little or no influence,Other (please specify):;Start a free trial;Vis...,Angola,INR\tIndian rupee,6.438169e+09,Monthly,APL;Assembly;Bash/Shell;C#;C++;Clojure;COBOL;C...,APL;Assembly;Bash/Shell;C#;C++;Clojure;COBOL;C...,Cassandra;Couchbase;Cloud Firestore;DynamoDB;E...,Cassandra;Couchbase;Cloud Firestore;DynamoDB;E...,AWS;Colocation;Microsoft Azure;Oracle Cloud In...,AWS;Colocation;Microsoft Azure;Oracle Cloud In...,Angular;ASP.NET;ASP.NET Core ;Ruby on Rails;Sv...,Angular;ASP.NET Core ;Ruby on Rails;Svelte;Sym...,.NET;Capacitor;Electron;Flutter;GTK;Hadoop;Ion...,.NET;Capacitor;Electron;Flutter;GTK;Hadoop;Ion...,Ansible;Unreal Engine;Yarn,Ansible;Unreal Engine;Yarn,Android Studio;Vim;Xcode,Android Studio;Vim;Xcode,BSD;Windows Subsystem for Linux (WSL),BSD;Windows Subsystem for Linux (WSL),Git;Mercurial;SVN,Code editor;Command-line;Version control hosti...,NaN,NaN,Airtable;Asana;Cerri;ClickUp;Confluence;DingTa...,Airtable;Asana;Cerri;ClickUp;Confluence;DingTa...,Cisco Webex Teams;Zoom,Cisco Webex Teams;Zoom,Indifferent,I have never visited Stack Overflow or the Sta...,NaN,Yes,A few times per month or weekly,"Yes, somewhat",45-54 years old,"Man;Woman;Non-binary, genderqueer, or gender n...",Yes,Bisexual;Straight / Heterosexual;Gay or Lesbia...,White;Indian;European;North American;Middle Ea...,I am deaf / hard of hearing;I am blind / have ...,"I have a mood or emotional disorder (e.g., dep...",Yes,Independent contributor,45.0,Strongly disagree,Strongly disagree,Strongly disagree,Disagree,Agree,Neither agree nor disagree,Agree,Never,1-2 times a week,6-10 times a week,30-60 minutes a day,30-60 minutes a day,Somewhat short,Innersource initiative;DevOps function;Microse...,Yes,NaN,NaN,Appropriate in length,Difficult,NaN

### Grouping and Aggregating the dataset

In [72]:
df["CompTotal"].head(10)

6891     55000000.0
38512     1200000.0
43639      700000.0
43690      100000.0
2448        40000.0
6242        40000.0
23223       40000.0
49273        6000.0
55665         200.0
3886            1.0
Name: CompTotal, dtype: float64

In [74]:
df["CompTotal"].median() #median salary of developers

77500.0

In [75]:
df.median()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

ResponseId                   36634.5
CompTotal                    77500.0
VCHostingPersonal use            NaN
VCHostingProfessional use        NaN
WorkExp                          8.0
ConvertedCompYearly          67845.0
dtype: float64

In [76]:
df.describe()

,ResponseId,CompTotal,VCHostingPersonal use,VCHostingProfessional use,WorkExp,ConvertedCompYearly
count,73268.000000,3.842200e+04,0.0,0.0,36769.000000,3.807100e+04
mean,36634.500000,2.342434e+52,NaN,NaN,10.242378,1.707613e+05
std,21150.794099,4.591478e+54,NaN,NaN,8.706850,7.814132e+05
min,1.000000,0.000000e+00,NaN,NaN,0.000000,1.000000e+00
25%,18317.750000,3.000000e+04,NaN,NaN,4.000000,3.583200e+04
50%,36634.500000,7.750000e+04,NaN,NaN,8.000000,6.784500e+04
75%,54951.250000,1.540000e+05,NaN,NaN,15.000000,1.200000e+05
max,73268.000000,9.000000e+56,NaN,NaN,50.000000,5.000000e+07

In [77]:
df["CompTotal"].count()

38422

In [79]:
df["CodingActivities"].head(10)

6891     Contribute to open-source projects;Freelance/c...
38512    Hobby;Contribute to open-source projects;Boots...
43639                       Hobby;Bootstrapping a business
43690    Hobby;Contribute to open-source projects;Boots...
2448     Hobby;Contribute to open-source projects;Schoo...
6242       Freelance/contract work;School or academic work
23223                              School or academic work
49273    Hobby;Contribute to open-source projects;Boots...
55665    Hobby;Contribute to open-source projects;Freel...
3886              Hobby;Contribute to open-source projects
Name: CodingActivities, dtype: object

In [80]:
df["CodingActivities"].value_counts()

Hobby                                                                                                                                        18118
I don’t code outside of work                                                                                                                  7311
Hobby;Contribute to open-source projects                                                                                                      6549
Hobby;Freelance/contract work                                                                                                                 3554
Hobby;School or academic work                                                                                                                 3016
Freelance/contract work                                                                                                                       2189
Hobby;Bootstrapping a business                                                                                                                2136
Hobby;Contribute to open-source projects;Freelance/contract work                                                                              2028
Hobby;Contribute to open-source projects;School or academic work                                                                              1254
School or academic work                                                                                                                       1208
Bootstrapping a business                                                                                                                      1163
Hobby;Contribute to open-source projects;Bootstrapping a business                                                                             1133
Hobby;Bootstrapping a business;Freelance/contract work                                                                                         929
Contribute to open-source projects                                                                                                             917
Hobby;Contribute to open-source projects;Bootstrapping a business;Freelance/contract work                                                      824
Hobby;Freelance/contract work;School or academic work                                                                                          767
Other (please specify):                                                                                                                        735
Hobby;Other (please specify):                                                                                                                  674
Contribute to open-source projects;Freelance/contract work                                                                                     528
Hobby;Contribute to open-source projects;Freelance/contract work;School or academic work                                                       526
Bootstrapping a business;Freelance/contract work                                                                                               503
Hobby;Contribute to open-source projects;Bootstrapping a business;Freelance/contract work;School or academic work                              281
Hobby;Bootstrapping a business;School or academic work                                                                                         262
Contribute to open-source projects;Bootstrapping a business;Freelance/contract work                                                            261
Freelance/contract work;School or academic work                                                                                                256
Contribute to open-source projects;Bootstrapping a business                                                                                    217
Hobby;Contribute to open-source projects;Other (please specify):                                                                               178
Contribute to open-source projects;School or academic work                                                                                     169
Hobby;Bootstrapping a business;Freelance/contract work;School or academic work                                                                 165
Hobby;Contribute to open-source projects;Bootstrapping a business;School or academic work                                                      152
Contribute to open-source projects;Freelance/contract work;School or academic work                                                             103
Hobby;Freelance/contract work;Other (please specify):                                                                                          102
Bootstrapping a business;School or academic work                                                                                                76
Hobby;Other (please specify):;School or academic work                                                                                           73
Bootstrapping a business;Freelance/contract work;School or academic work                                                                        63
Freelance/contract work;Other (please specify):                                                                                                 57
Contribute to open-source projects;Other (please specify):                                                                                      45
Hobby;Bootstrapping a business;Other (please specify):                                                                                          44
Contribute to open-source projects;Bootstrapping a business;School or academic work                                                             35
Other (please specify):;School or academic work                                                                                                 32
Hobby;Contribute to open-source projects;Freelance/contract work;Other (please specify):                                                        31
Hobby;Contribute to open-source projects;Other (please specify):;School or academic work                                                        29
Contribute to open-source projects;Bootstrapping a business;Freelance/contract work;School or academic work                                     27
Bootstrapping a business;Other (please specify):                                                                                                23
Hobby;Contribute to open-source projects;Bootstrapping a business;Other (please specify):                                                       20
Bootstrapping a business;Freelance/contract work;Other (please specify):                                                                        18
Hobby;Bootstrapping a business;Freelance/contract work;Other (please specify):                                                                  17
Hobby;Contribute to open-source projects;Bootstrapping a business;Freelance/contract work;Other (please specify):                               15
Hobby;Contribute to open-source projects;Bootstrapping a business;Freelance/contract work;Other (please specify):;School or academic work       14
Contribute to open-source projects;Freelance/contract work;Other (please specify):                                                              13
Hobby;Freelance/contract work;Other (please specify):;School or academic work                                                                   12
Contribute to open-source projects;Other (please specify):;School or academic work                                                               8
Freelance/contract work;Other (please specify):;School or academic work                                                                          7
Hobby;Contribute to open-source projects;Freelance/contract work;Other (please specify):;School or academic work                                 7
Hobby;Bootstrapping a business;Other (please specify):;School or academic work                                                                   6
Contribute to open-source projects;Bootstrapping a business;Other (please specify):                                                              5
Hobby;Bootstrapping a business;Freelance/contract work;Other (please specify):;School or academic work                                           4
Contribute to open-source projects;Bootstrapping a business;Other (please specify):;School or academic work                                      3
Contribute to open-source projects;Freelance/contract work;Other (please specify):;School or academic work                                       2
Hobby;Contribute to open-source projects;Bootstrapping a business;Other (please specify):;School or academic work                                2
Contribute to open-source projects;Bootstrapping a business;Freelance/contract work;Other (please specify):                                      1
Contribute to open-source projects;Bootstrapping a business;Freelance/contract work;Other (please specify):;School or academic work              1
Bootstrapping a business;Other (please specify):;School or academic work                                                                         1
Name: CodingActivities, dtype: int64

In [82]:
schema_df.head(5)

,qid,qname,question,force_resp,type,selector
0,QID16,S0,"<div><span style=""font-size:19px;""><strong>Hel...",False,DB,TB
1,QID12,MetaInfo,Browser Meta Info,False,Meta,Browser
2,QID1,S1,"<span style=""font-size:22px; font-family: aria...",False,DB,TB
3,QID2,MainBranch,Which of the following options best describes ...,True,MC,SAVR
4,QID296,Employment,Which of the following best describes your cur...,False,MC,MAVR

In [86]:
schema_df["qname"]

0                       S0
1                 MetaInfo
2                       S1
3               MainBranch
4               Employment
5               RemoteWork
6         CodingActivities
7                       S2
8                  EdLevel
9                LearnCode
10         LearnCodeOnline
11    LearnCodeCoursesCert
12               YearsCode
13            YearsCodePro
14                 DevType
15                 OrgSize
16       PurchaseInfluence
17              BuyNewTool
18                 Country
19                Currency
20               CompTotal
21                CompFreq
22                      S3
23                Language
24                Database
25                Platform
26                Webframe
27                MiscTech
28               ToolsTech
29          NEWCollabTools
30                   OpSys
31    VersionControlSystem
32           VCInteraction
33               VCHosting
34        OfficeStackAsync
35         OfficeStackSync
36              Blockchain
37                      S4
38              NEWSOSites
39             SOVisitFreq
40               SOAccount
41              SOPartFreq
42                  SOComm
43                      S5
44                     Age
45                  Gender
46                   Trans
47               Sexuality
48               Ethnicity
49           Accessibility
50            MentalHealth
51                      S6
52                 TBranch
53                  ICorPM
54                 WorkExp
55               Knowledge
56               Frequency
57           TimeSearching
58           TimeAnswering
59              Onboarding
60        ProfessionalTech
61            SOTeamsUsage
62               TrueFalse
63                      S7
64            SurveyLength
65              SurveyEase
66             Knowledge_1
67             Knowledge_2
68             Knowledge_3
69             Knowledge_4
70             Knowledge_5
71             Knowledge_6
72             Knowledge_7
73             Frequency_1
74             Frequency_2
75             Frequency_3
76             TrueFalse_1
77             TrueFalse_2
78             TrueFalse_3
Name: qname, dtype: object

In [91]:
df["EdLevel"].value_counts(normalize=True) #Analyzing the education level

Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          0.423020
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       0.216373
Some college/university study without earning a degree                                0.130304
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)    0.110436
Associate degree (A.A., A.S., etc.)                                                   0.031242
Other doctoral degree (Ph.D., Ed.D., etc.)                                            0.030306
Primary/elementary school                                                             0.025234
Something else                                                                        0.017423
Professional degree (JD, MD, etc.)                                                    0.015663
Name: EdLevel, dtype: float64

In [92]:
df["Country"].value_counts()

United States of America                                13543
India                                                    6639
Germany                                                  5395
United Kingdom of Great Britain and Northern Ireland     4190
Canada                                                   2490
                                                        ...
Seychelles                                                  1
Monaco                                                      1
Solomon Islands                                             1
Burkina Faso                                                1
Djibouti                                                    1
Name: Country, Length: 180, dtype: int64

In [94]:
country_df=df.groupby(["Country"])

In [98]:
country_df.get_group("India").head(5)  #getting the responses from only India

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
64897,64898,I am a developer by profession,"Employed, full-time",Fully remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Udemy,26,7,"Developer, back-end",500 to 999 employees,I have some influence,Start a free trial;Visit developer communities...,India,INR\tIndian rupee,510000000.0,Yearly,Go;JavaScript,C;C++;Go;Java;Rust,Oracle,Couchbase;PostgreSQL,NaN,NaN,React.js,NaN,NaN,NaN,NaN,NaN,IntelliJ,IntelliJ,macOS,macOS,Git,Command-line,NaN,NaN,Jira Work Management,Jira Work Management,Microsoft Teams;Slack,Slack,Unsure,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Less than once per month or monthly,"Yes, somewhat",35-44 years old,Man,No,Straight / Heterosexual,Indian,None of the above,"I have a mood or emotional disorder (e.g., dep...",Yes,Independent contributor,7.0,Agree,Agree,Agree,Agree,Agree,Agree,Neither agree nor disagree,1-2 times a week,1-2 times a week,3-5 times a week,30-60 minutes a day,Less than 15 minutes a day,Somewhat long,DevOps function;Continuous integration (CI) an...,Yes,Yes,Yes,Too long,Easy,6577582.0
12131,12132,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",School or academic work,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Udemy;edX,20,15,"Developer, full-stack;Developer, back-end;DevO...",100 to 499 employees,I have little or no influence,Start a free trial;Visit developer communities...,India,INR\tIndian rupee,25000000.0,Yearly,PHP,C#;HTML/CSS;JavaScript;PowerShell;SQL;TypeScript,MongoDB;MySQL;Oracle;Firebase Realtime Databas...,Microsoft SQL Server,Oracle Cloud Infrastructure,Microsoft Azure,Angular;Angular.js;Next.js;React.js,ASP.NET;ASP.NET Core ;Blazor;jQuery,NaN,NaN,NaN,NaN,NaN,NaN,Linux-based;Windows,NaN,Git;Other (please specify):,Command-line;Version control hosting service w...,NaN,NaN,NaN,NaN,Cisco Webex Teams;Google Chat;Zoom,Microsoft Teams,Favorable,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,"Yes, definitely",45-54 years old,Man,No,Prefer not to say,Indian,None of the above,None of the above,Yes,Independent contributor,15.0,Agree,Agree,Disagree,Strongly agree,Strongly agree,Neither agree nor disagree,Neither agree nor disagree,1-2 times a week,1-2 times a week,1-2 times a week,15-30 minutes a day,15-30 minutes a day,Somewhat long,None of these,No,Yes,Yes,Too long,Neither easy nor difficult,322430.0
25937,25938,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","School (i.e., University, College, etc)",NaN,NaN,25,21,"Developer, front-end;Developer, full-stack;Dev...","1,000 to 4,999 employees",I have some influence,Visit developer communities like Stack Overflo...,India,INR\tIndian rupee,20000000.0,Yearly,C++;Dart;HTML/CSS;Java;JavaScript;Kotlin;Objec...,NaN,Cassandra;CouchDB;Cloud Firestore;DynamoDB;Ela...,NaN,AWS;Firebase;Google Cloud;Heroku;Oracle Cloud ...,NaN,Angular;Django;Flask;Node.js,NaN,Apache Kafka;Apache Spark;Electron;Flutter;Ker...,NaN,Docker;Kubernetes;npm;Terraform,NaN,Android Studio;IntelliJ;Sublime Text;Vim;Visua...,NaN,Linux-based;macOS,Linux-based;macOS,Git,Command-line,NaN,NaN,Confluence,NaN,Google Chat;Microsoft Teams;Zoom,NaN,Indifferent,NaN,A few times per week,Yes,A few times per month or weekly,"Yes, somewhat",35-44 years old,Man,No,Straight / Heterosexual,Indian;Asian,None of the above,None of the above,Yes,People manager,22.0,Agree,Agree,Disagree,Strongly disagree,Agree,Agree,Disagree,1-2 times a week,10+ times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Just right,Innersource initiative;DevOps function;Microse...,Yes,Yes,Yes,Too long,Easy,257944.0
9795,9796,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,Coursera;Udemy;edX,12,8,"Developer, full-stack;Developer, back-end;Engi...",10 to 19 employees,I have some influence,Start a free trial;Visit developer communities...,India,INR\tIndian rupee,15000000.0,Yearly,Bash/Shell;C++;Go;HTML/CSS;JavaScript;Python;T...,Bash/Shell;C++;Go;HTML/CSS;JavaScript;Python;R...,DynamoDB;PostgreSQL;Redis,DynamoDB;PostgreSQL;Redis,AWS,AWS,Django;Express;Node.js;React.js,Django;Express;FastAPI;React.js,Qt;Torch/PyTorch,Qt;Torch/PyTorch,Docker;Yarn,Docker;Kubernetes;npm;Terraform,IPython/Jupyter;Nano;Qt Creator;Visual Studio ...,IPython/Jupyter;Nano;Qt Creator;Visual Studio ...,Linux-based;macOS,Linux-based;macOS,Git,Code editor;Command-line,NaN,NaN,Confluence,Confluence,Slack;Zoom,Slack;Zoom,Unfavorable,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per week,"Yes, definitely",25-34 years old,Man,No,Straight / Heterosexual,Indian;South Asian,None of the above,None of the above,Yes,People manager,8.0,Agree,Neither agree nor disagree,Agree,Agree,Agree,Neither agree nor disagree,Agree,1-2 times a week,1-2 times a week,Never,60-120 minutes a day,30-60 minutes a day,Somewhat long,None of these,Yes,Yes,Yes,Too long,Neither easy nor difficult,193458.0
57353,57354,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Contribute to open-source projects;Schoo...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;W...,NaN,22,15,"Engineer, site reliability;Developer, back-end...","1,000 to 4,999 employees",I have a great deal of influence,Start a free trial;Visit developer communities...,India,INR\tIndian rupee,15000000.0,Yearly,Go;HTML/CSS;Java;JavaScript;Kotlin;Python;Soli...,Go;HTML/CSS;Java;JavaScript;Kotlin;Lua;Python;...,Cloud Firestore;DynamoDB;PostgreSQL;Firebase R...,Cloud Firestore;DynamoDB;PostgreSQL;Firebase R...,AWS;Firebase;Google Cloud,AWS;Firebase;Google Cloud;Microsoft Azure,Gatsby;Node.js;React.js,React.js;Svelte;Vue.js,Apache Kafka;Apache Spark;Hadoop;NumPy;Pandas;...,Apache Kafka;Apache Spark;Hadoop;NumPy;Pandas;...,Docker;Kubernetes;npm;Terraform;Yarn,Docker;Kubernetes;npm;Terraform,Android Studio;IntelliJ;Vim;Visual Studio Code,Android Studio;IntelliJ;Vim;Visual Studio Code,Windows,macOS;Windows Subsystem for Linux (WSL),Git,Command-line,NaN,NaN,Jira Work Management;Notion,Jira Work Management;Notion,Google Chat;Slack;Zoom,Google Chat;Slack;Zoom,Favorable,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,Indian,None of the above,None of the above,Yes,People manager,15.0,Agree,Agree,Agree,Agree,Agree,Agree,Agree,1-2 times a week,1-2 times a week,1-2 times a week,15-30 minutes a day,15-30 minutes a day,Somewhat long,DevOps function;Microservices;Continuous integ...,Yes,Yes,No,Appropriate in length,Neither easy nor difficult,193458.0

In [100]:
India_filt=df["Country"]=="India"
df.loc[India_filt]

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,Country,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSysProfessional use,OpSysPersonal use,VersionControlSystem,VCInteraction,VCHostingPersonal use,VCHostingProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,Blockchain,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
64897,64898,I am a developer by profession,"Employed, full-time",Fully remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Udemy,26,7,"Developer, back-end",500 to 999 employees,I have some influence,Start a free trial;Visit developer communities...,India,INR\tIndian rupee,510000000.0,Yearly,Go;JavaScript,C;C++;Go;Java;Rust,Oracle,Couchbase;PostgreSQL,NaN,NaN,React.js,NaN,NaN,NaN,NaN,NaN,IntelliJ,IntelliJ,macOS,macOS,Git,Command-line,NaN,NaN,Jira Work Management,Jira Work Management,Microsoft Teams;Slack,Slack,Unsure,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Less than once per month or monthly,"Yes, somewhat",35-44 years old,Man,No,Straight / Heterosexual,Indian,None of the above,"I have a mood or emotional disorder (e.g., dep...",Yes,Independent contributor,7.0,Agree,Agree,Agree,Agree,Agree,Agree,Neither agree nor disagree,1-2 times a week,1-2 times a week,3-5 times a week,30-60 minutes a day,Less than 15 minutes a day,Somewhat long,DevOps function;Continuous integration (CI) an...,Yes,Yes,Yes,Too long,Easy,6577582.0
12131,12132,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",School or academic work,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,Udemy;edX,20,15,"Developer, full-stack;Developer, back-end;DevO...",100 to 499 employees,I have little or no influence,Start a free trial;Visit developer communities...,India,INR\tIndian rupee,25000000.0,Yearly,PHP,C#;HTML/CSS;JavaScript;PowerShell;SQL;TypeScript,MongoDB;MySQL;Oracle;Firebase Realtime Databas...,Microsoft SQL Server,Oracle Cloud Infrastructure,Microsoft Azure,Angular;Angular.js;Next.js;React.js,ASP.NET;ASP.NET Core ;Blazor;jQuery,NaN,NaN,NaN,NaN,NaN,NaN,Linux-based;Windows,NaN,Git;Other (please specify):,Command-line;Version control hosting service w...,NaN,NaN,NaN,NaN,Cisco Webex Teams;Google Chat;Zoom,Microsoft Teams,Favorable,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,"Yes, definitely",45-54 years old,Man,No,Prefer not to say,Indian,None of the above,None of the above,Yes,Independent contributor,15.0,Agree,Agree,Disagree,Strongly agree,Strongly agree,Neither agree nor disagree,Neither agree nor disagree,1-2 times a week,1-2 times a week,1-2 times a week,15-30 minutes a day,15-30 minutes a day,Somewhat long,None of these,No,Yes,Yes,Too long,Neither easy nor difficult,322430.0
25937,25938,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Contribute to open-source projects;Boots...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","School (i.e., University, College, etc)",NaN,NaN,25,21,"Developer, front-end;Developer, full-stack;Dev...","1,000 to 4,999 employees",I have some influence,Visit developer communities like Stack Overflo...,India,INR\tIndian rupee,20000000.0,Yearly,C++;Dart;HTML/CSS;Java;JavaScript;Kotlin;Objec...,NaN,Cassandra;CouchDB;Cloud Firestore;DynamoDB;Ela...,NaN,AWS;Firebase;Google Cloud;Heroku;Oracle Cloud ...,NaN,Angular;Django;Flask;Node.js,NaN,Apache Kafka;Apache Spark;Electron;Flutter;Ker...,NaN,Docker;Kubernetes;npm;Terraform,NaN,Android Studio;IntelliJ;Sublime Text;Vim;Visua...,NaN,Linux-based;macOS,Linux-based;macOS,Git,Command-line,NaN,NaN,Confluence,NaN,Google Chat;Microsoft Teams;Zoom,NaN,Indifferent,NaN,A few times per week,Yes,A few times per month or weekly,"Yes, somewhat",35-44 years old,Man,No,Straight / Heterosexual,Indian;Asian,None of the above,None of the above,Yes,People manager,22.0,Agree,Agree,Disagree,Strongly disagree,Agree,Agree,Disagree,1-2 times a week,10+ times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Just right,Innersource initiative;DevOps function;Microse...,Yes,Yes,Yes,Too long,Easy,257944.0
9795,9796,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,Coursera;Udemy;edX,12,8,"Developer, full-stack;Developer, back-end;Engi...",10 to 19 employees,I have some influence,Start a free trial;Visit developer communities...,India,INR\tIndian rupee,15000000.0,Yearly,Bash/Shell;C++;Go;HTML/CSS;JavaScript;Python;T...,Bash/Shell;C++;Go;HTML/CSS;JavaScript;Python;R...,DynamoDB;PostgreSQL;Redis,DynamoDB;PostgreSQL;Redis,AWS,AWS,Django;Express;Node.js;React.js,Django;Express;FastAPI;React.js,Qt;Torch/PyTorch,Qt;Torch/PyTorch,Docker;Yarn,Docker;Kubernetes;npm;Terraform,IPython/Jupyter;Nano;Qt Creator;Visual Studio ...,IPython/Jupyter;Nano;Qt Creator;Visual Studio ...,Linux-based;macOS,Linux-based;macOS,Git,Code editor;Command-line,NaN,NaN,Confluence,Confluence,Slack;Zoom,Slack;Zoom,Unfavorable,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per week,"Yes, definitely",25-34 years old,Man,No,Straight / Heterosexual,Indian;South Asian,None of the above,None of the above,Yes,People manager,8.0,Agree,Neither agree nor disagree,Agree,Agree,Agree,Neither agree nor disagree,Agree,1-2 times a week,1-2 times a week,Never,60-120 minutes a day,30-60 minutes a day,Somewhat long,None of these,Yes,Yes,Yes,Too long,Neither easy nor difficult,193458.0
57353,57354,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Contribute to open-source projects;Schoo...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;W...,NaN,22,15,"Engineer, site reliability;Developer, back-end...","1,000 to 4,999 employees",I have a great deal of influence,Start a free trial;Visit developer communities...,India,INR\tIndian rupee,15000000.0,Yearly,Go;HTML/CSS;Java;JavaScript;Kotlin;Python;Soli...,Go;HTML/CSS;Java;JavaScript;Kotlin;Lua;Python;...,Cloud Firestore;DynamoDB;PostgreSQL;Firebase R...,Cloud Firestore;DynamoDB;PostgreSQL;Firebase R...,AWS;Firebase;Google Cloud,AWS;Firebase;Google Cloud;Microsoft Azure,Gatsby;Node.js;React.js,React.js;Svelte;Vue.js,Apache Kafka;Apache Spark;Hadoop;NumPy;Pandas;...,Apache Kafka;Apache Spark;Hadoop;NumPy;Pandas;...,Docker;Kubernetes;npm;Terraform;Yarn,Docker;Kubernetes;npm;Terraform,Android Studio;IntelliJ;Vim;Visual Studio Code,Android Studio;IntelliJ;Vim;Visual Studio Code,Windows,macOS;Windows Subsystem for Linux (WSL),Git,Command-line,NaN,NaN,Jira Work Management;Notion,Jira Work Management;Notion,Google Chat;Slack;Zoom,Google Chat;Slack;Zoom,Favorable,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",35-44 years old,Man,No,Straight / Heterosexual,Indian,None of the above,None of the above,Yes,People manager,15.0,Agree,Agree,Agree,Agree,Agree,Agree,Agree,1-2 times a week,1-2 times a week,1-2 times a week,15-30 minutes a day,15-30 minutes a day,Somewhat long,DevOps function;Microservices;Continuous integ...,Yes,Yes,No,Appropriate in length,Neither easy nor difficult,193458.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73133,73134,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,Udemy,5,2,"Engineer, site reliability;DevOps specialist;C...","10,000 or more employees",I have little or no influence,Start a free trial;Visit developer communities...,India,INR\tIndian rupee,NaN,Monthly,Bash/Shell;Python,C;Go;Haskell,NaN,NaN,AWS,AWS;Google Cloud;Heroku,NaN,NaN,NaN,NaN,Ansible;Docker;Kubernetes;Terraform,Ansible;Docker;Kubernetes;Terraform,Notepad++;Vim;Visual Studio Code,Notepad++;Vim;Visual Studio Code,Windows;Windows Subsystem for Linux (WSL),Windows;Windows Subsystem for Linux (WSL),Git,Command-line,NaN,NaN,Confluence,NaN,Microsoft Teams,Google Chat;Slack,Indifferent,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,Neutral,NaN,Man,No,NaN,Indian,NaN,"I have a mood or emotional disorder (e.g., dep...",Yes,Independent contributor,5.0,Agree,Agree,Disagree,Strongly disagree,Disagree,Agree,Strongly agree,6-10 times a week,6-10 times a week,6-10 times a week,60-120 minutes a day,30-60 minutes a day,Very short,None of these,No,No,No,Too short,Easy,NaN
73178,73179,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Bootstrapping a business;Freelance/contr...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Stack Overflow;V...,Udemy;Pluralsight,14,10,"Developer, front-end;Developer, full-stack",I don’t know,I have little or no influence,Start a free trial;Visit developer communities...,India,INR\tIndian rupee,NaN,NaN,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;Python;Rust;SQL;TypeScript,NaN,NaN,Firebase;Heroku;VMware,AWS;Firebase;Microsoft Azure,Angular;Next.js;React.js,Django;Express;Flask;Gatsby;Next.js;Node.js;Re...,NaN,NaN,Docker;npm;Yarn,Docker;npm,Notepad++;Visual Studio;Visual Studio Code,Visual Studio Code,Linux-based;Windows,Linux-based;Windows,Git,Command-line,NaN,NaN,Confluence,NaN,Microsoft Teams;Zoom,Zoom,Indifferent,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,Less than once per month or monthly,"Yes, somewhat",25-34 years old,Man,No,Straight / Heterosexual,Indian;Asian;South Asian,None of the above,None of the above,Yes,Independent contributor,11.0,Agree,Neither agree nor disagree,Agree,Strongly agree,Agree,Neither agree nor disagree,Agree,1-2 times a week,1-2 times a week,Never,30-60 minutes a day,15-30 minutes a day,Just right,DevOps function;Microservices;Continuous integ...,No,Yes,Yes,Appropriate in length,Neither easy nor difficult,NaN
73193,73194,"I used to be a developer by profession, but no...","Employed, full-time",Fully remote,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Video-b...,Coursera;Udemy,20,18,"Senior Executive (C-Suite, VP, etc.)",NaN,NaN,Start a free trial;Ask developers I know/work ...,India,NaN,NaN,NaN,HTML/CSS;JavaScript,Go;HTML/CSS;Java;JavaScript;TypeScript,MongoDB;Firebase Realtime Database,MongoDB;PostgreSQL;Redis,AWS,AWS;Microsoft Azure,Angular.js;Express;Node.js;React.js,React.js,React Native,Apache Kafka;Flutter;React Native;Spring,Docker;Kubernetes,Docker;Kubernetes;Terraform;Yarn,Sublime Text;Vim;Visual Studio Code,Eclipse;Sublime Text;Vim;Visual Studio Code,macOS,macOS,Git,Command-line,NaN,NaN,Confluence;Jira Work Management,Confluence;Jira Work Management,Slack;Zoom,Slack;Zoom,Indifferent,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,Less than once per month or monthly,"Yes, somewhat",35-44 years old,Man,No,Straight / Heterosexual,Indian,None of the above,None of the above,Yes,People manager,18.0,Strongly agree,Agree,Agree,Agree,Agree,Disagree,Disagree,1-2 times a week,1-2 times a week,1-2 times a week,15-30 minutes a day,15-30 minutes a day,Somewhat long,DevOps function;Microservices;Developer portal...,Yes,Yes,Yes,Appropriate in length,Easy,NaN
73255,73256,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby;Freelance/contract work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,14,7,"Developer, full-stack",100 to 499 employees,I have little or no influence,NaN,India,INR\tIndian rupee,NaN,Monthly,Bash/Shell;C#;HTML/CSS;JavaScript;Perl;PowerSh...,Bash/Shell;C#;HTML/CSS;JavaScript;Perl;PowerSh...,Microsoft SQL Server;MongoDB,Microsoft SQL Server;MongoDB,NaN,NaN,Angular;ASP.NET Core,Angular;ASP.NET Core ;React.js,.NET,.NET,Docker;Kubernetes;npm,Docker;Kubernetes;npm,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows,Windows,Git,Command-line;Version control hosting service w...,NaN,NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Favorable,Collectives on Stack Overflow;Stack Overflow;S...,Daily or almost daily,Yes,Less than once per month or monthly,"Yes, somewhat",25-34 years old,Man,No,Prefer not to say,Indian,None of the above,None of the above,Yes,Independent contributor,7.0,Neither agree nor disagree,Agree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,Neither agree nor disagree,1-2 times a week,1-2 times a week,1-2 times a week,60-120 minutes a day,Less than 15 minutes a day,Somewhat long,DevOps function;Microservices;Continuous integ...,Yes,Yes,Yes,Too long,Neither easy nor difficult,NaN
73257,73258,I am learning to code,"Student, full-time",NaN,NaN,"Secondary school (e.g. American high school, G...",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Written Tutorial...,NaN,7,NaN,NaN,NaN,NaN,Visit developer communities like Stack Overflo...,India,NaN,NaN,NaN,C;Python;SQL,C;C++,MySQL,NaN,NaN,NaN,NaN,NaN,.NET,NaN,NaN,NaN,Visual Studio;Visual Studio Code,Visual Studio Code,NaN,Windows,Git,Command-line,NaN,NaN,NaN,NaN,Microsoft Teams;Zoom,NaN,Very unfavorable,Stack Overflow;Stack Exchange,Less than once per month or monthly,Yes,Less than once per month or monthly,"No, not at all",Under 18 years old,Man,No,Straight / Heterosexual,Indian,None of the above,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN

In [101]:
df.loc[India_filt]["EdLevel"].value_counts()

Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          4121
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       1129
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     704
Some college/university study without earning a degree                                 334
Primary/elementary school                                                              158
Something else                                                                          80
Professional degree (JD, MD, etc.)                                                      46
Other doctoral degree (Ph.D., Ed.D., etc.)                                              23
Associate degree (A.A., A.S., etc.)                                                     21
Name: EdLevel, dtype: int64

In [104]:
country_df["EdLevel"].value_counts()

Country      EdLevel
Afghanistan  Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          26
             Primary/elementary school                                                              9
             Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                        8
             Some college/university study without earning a degree                                 8
             Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     6
                                                                                                   ..
Zimbabwe     Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          12
             Some college/university study without earning a degree                                11
             Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     5
             Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                        1
             Primary/elementary school                                                              1
Name: EdLevel, Length: 1137, dtype: int64

In [105]:
country_df["EdLevel"].value_counts().loc["India"]

EdLevel
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          4121
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       1129
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     704
Some college/university study without earning a degree                                 334
Primary/elementary school                                                              158
Something else                                                                          80
Professional degree (JD, MD, etc.)                                                      46
Other doctoral degree (Ph.D., Ed.D., etc.)                                              23
Associate degree (A.A., A.S., etc.)                                                     21
Name: EdLevel, dtype: int64

In [108]:
country_df["CompTotal"].median().loc["India"] #mean salary of Indian Developers

885000.0

In [111]:
country_df["CompTotal"].agg(["mean","median"]) #mean and median salary of developers in different countries

                                              mean      median
Country
Afghanistan                           3.808414e+06      6000.0
Albania                               5.104657e+05      5500.0
Algeria                               8.754444e+04     75000.0
Andorra                               7.677250e+04     31500.0
Angola                                1.287990e+09    600000.0
...                                            ...         ...
Venezuela, Bolivarian Republic of...  4.498590e+03      1094.0
Viet Nam                              4.443807e+07  15000000.0
Yemen                                 1.071667e+05     20750.0
Zambia                                5.613333e+03      6200.0
Zimbabwe                              9.445000e+04       950.0

[180 rows x 2 columns]

In [113]:
India_filt=df["Country"]=="India"
df.loc[India_filt]["LanguageHaveWorkedWith"].str.contains("Python").sum()

3081

In [116]:
India_filt=df["Country"]=="India"
df.loc[India_filt]["DevType"].str.contains("Data scientist").sum()

263

In [119]:
country_df["LanguageHaveWorkedWith"].apply(lambda x:x.str.contains("Python").sum())

Country
Afghanistan                              25
Albania                                  19
Algeria                                  19
Andorra                                   4
Angola                                    3
                                       ...
Venezuela, Bolivarian Republic of...     52
Viet Nam                                136
Yemen                                     4
Zambia                                    6
Zimbabwe                                 11
Name: LanguageHaveWorkedWith, Length: 180, dtype: int64

In [122]:
country_df["LanguageHaveWorkedWith"].apply(lambda x:x.str.contains("Python").sum()).loc["Canada"] #number of people from canada who work with python

1272

In [123]:
country_respondents=df["Country"].value_counts()
country_respondents

United States of America                                13543
India                                                    6639
Germany                                                  5395
United Kingdom of Great Britain and Northern Ireland     4190
Canada                                                   2490
                                                        ...
Seychelles                                                  1
Monaco                                                      1
Solomon Islands                                             1
Burkina Faso                                                1
Djibouti                                                    1
Name: Country, Length: 180, dtype: int64

In [124]:
country_uses_python=country_df["LanguageHaveWorkedWith"].apply(lambda x:x.str.contains("Python").sum())
country_uses_python

Country
Afghanistan                              25
Albania                                  19
Algeria                                  19
Andorra                                   4
Angola                                    3
                                       ...
Venezuela, Bolivarian Republic of...     52
Viet Nam                                136
Yemen                                     4
Zambia                                    6
Zimbabwe                                 11
Name: LanguageHaveWorkedWith, Length: 180, dtype: int64

In [125]:
python_df=pd.concat([country_respondents,country_uses_python],axis="columns",sort=False)

In [126]:
python_df

,Country,LanguageHaveWorkedWith
United States of America,13543,7017
India,6639,3081
Germany,5395,2674
United Kingdom of Great Britain and Northern Ireland,4190,2082
Canada,2490,1272
...,...,...
Seychelles,1,0
Monaco,1,0
Solomon Islands,1,1
Burkina Faso,1,1
Djibouti,1,0

##### Above table shows the total number of respondents from each country and that how many of them actually work with python

In [128]:
python_df.rename(columns={"Country":"Number of Respondents","LanguageHaveWorkedWith":"Works with Python"},inplace=True)

In [129]:
python_df

,Number of Respondents,Works with Python
United States of America,13543,7017
India,6639,3081
Germany,5395,2674
United Kingdom of Great Britain and Northern Ireland,4190,2082
Canada,2490,1272
...,...,...
Seychelles,1,0
Monaco,1,0
Solomon Islands,1,1
Burkina Faso,1,1
Djibouti,1,0

In [130]:
python_df["Percentage of Python devs"]=(python_df["Works with Python"]/python_df["Number of Respondents"])*100

In [131]:
python_df

,Number of Respondents,Works with Python,Percentage of Python devs
United States of America,13543,7017,51.812745
India,6639,3081,46.407592
Germany,5395,2674,49.564411
United Kingdom of Great Britain and Northern Ireland,4190,2082,49.689737
Canada,2490,1272,51.084337
...,...,...,...
Seychelles,1,0,0.000000
Monaco,1,0,0.000000
Solomon Islands,1,1,100.000000
Burkina Faso,1,1,100.000000
Djibouti,1,0,0.000000

In [135]:
python_df.loc["India"]  #There are about 46% of python developers from India who entered the survey

Number of Respondents        6639.000000
Works with Python            3081.000000
Percentage of Python devs      46.407592
Name: India, dtype: float64

In [133]:
python_df.sort_values(by="Percentage of Python devs",ascending=False).head(50)

,Number of Respondents,Works with Python,Percentage of Python devs
Burkina Faso,1,1,100.000000
Solomon Islands,1,1,100.000000
Saint Kitts and Nevis,1,1,100.000000
Brunei Darussalam,1,1,100.000000
Fiji,2,2,100.000000
Papua New Guinea,2,2,100.000000
North Korea,4,4,100.000000
Lao People's Democratic Republic,7,6,85.714286
Timor-Leste,4,3,75.000000
Suriname,4,3,75.000000
Democratic Republic of the Congo,7,5,71.428571
Mali,10,7,70.000000
Kuwait,20,14,70.000000
Oman,13,9,69.230769
Belize,3,2,66.666667
Botswana,6,4,66.666667
Haiti,3,2,66.666667
Singapore,226,148,65.486726
Rwanda,20,13,65.000000
Benin,11,7,63.636364
Guinea,5,3,60.000000
Qatar,20,12,60.000000
Isle of Man,12,7,58.333333
Swaziland,7,4,57.142857
Côte d'Ivoire,14,8,57.142857
Israel,795,453,56.981132
Taiwan,233,132,56.652361
Guatemala,54,30,55.555556
Finland,468,260,55.555556
Cuba,31,17,54.838710
Switzerland,932,507,54.399142
Algeria,36,19,52.777778
China,632,332,52.531646
Ireland,332,174,52.409639
Sri Lanka,296,155,52.364865
Hong Kong (S.A.R.),184,96,52.173913
United States of America,13543,7017,51.812745
France,2328,1204,51.718213
Malta,39,20,51.282051
South Korea,229,117,51.091703
Canada,2490,1272,51.084337
United Republic of Tanzania,28,14,50.000000
Nepal,222,111,50.000000
Cameroon,34,17,50.000000
Turkmenistan,16,8,50.000000
Barbados,6,3,50.000000
Guyana,6,3,50.000000
Republic of Korea,72,36,50.000000
Ghana,86,43,50.000000
Palau,2,1,50.000000

### Cleaning the Data

In [136]:
import numpy as py

In [137]:
df.dtypes

ResponseId                          int64
MainBranch                         object
Employment                         object
RemoteWork                         object
CodingActivities                   object
EdLevel                            object
LearnCode                          object
LearnCodeOnline                    object
LearnCodeCoursesCert               object
YearsCode                          object
YearsCodePro                       object
DevType                            object
OrgSize                            object
PurchaseInfluence                  object
BuyNewTool                         object
Country                            object
Currency                           object
CompTotal                         float64
CompFreq                           object
LanguageHaveWorkedWith             object
LanguageWantToWorkWith             object
DatabaseHaveWorkedWith             object
DatabaseWantToWorkWith             object
PlatformHaveWorkedWith             object
PlatformWantToWorkWith             object
WebframeHaveWorkedWith             object
WebframeWantToWorkWith             object
MiscTechHaveWorkedWith             object
MiscTechWantToWorkWith             object
ToolsTechHaveWorkedWith            object
ToolsTechWantToWorkWith            object
NEWCollabToolsHaveWorkedWith       object
NEWCollabToolsWantToWorkWith       object
OpSysProfessional use              object
OpSysPersonal use                  object
VersionControlSystem               object
VCInteraction                      object
VCHostingPersonal use             float64
VCHostingProfessional use         float64
OfficeStackAsyncHaveWorkedWith     object
OfficeStackAsyncWantToWorkWith     object
OfficeStackSyncHaveWorkedWith      object
OfficeStackSyncWantToWorkWith      object
Blockchain                         object
NEWSOSites                         object
SOVisitFreq                        object
SOAccount                          object
SOPartFreq                         object
SOComm                             object
Age                                object
Gender                             object
Trans                              object
Sexuality                          object
Ethnicity                          object
Accessibility                      object
MentalHealth                       object
TBranch                            object
ICorPM                             object
WorkExp                           float64
Knowledge_1                        object
Knowledge_2                        object
Knowledge_3                        object
Knowledge_4                        object
Knowledge_5                        object
Knowledge_6                        object
Knowledge_7                        object
Frequency_1                        object
Frequency_2                        object
Frequency_3                        object
TimeSearching                      object
TimeAnswering                      object
Onboarding                         object
ProfessionalTech                   object
TrueFalse_1                        object
TrueFalse_2                        object
TrueFalse_3                        object
SurveyLength                       object
SurveyEase                         object
ConvertedCompYearly               float64
dtype: object

In [138]:
df["WorkExp"].head(10)

6891      2.0
38512     NaN
43639     NaN
43690     8.0
2448     15.0
6242      3.0
23223     7.0
49273     NaN
55665    14.0
3886     30.0
Name: WorkExp, dtype: float64

In [141]:
df["WorkExp"].unique()

array([ 2., nan,  8., 15.,  3.,  7., 14., 30.,  5., 13.,  4.,  0.,  1.,
        6., 18., 50., 12., 17.,  9., 10., 23., 24., 22., 25., 11., 36.,
       26., 45., 40., 19., 21., 35., 42., 34., 16., 41., 20., 37., 32.,
       29., 27., 28., 33., 39., 31., 38., 44., 47., 43., 49., 48., 46.])

In [144]:
df["WorkExp"].dtype

dtype('float64')

In [146]:
df["WorkExp"].mean()   #10 years of average coding experience for the developers

10.24237809023906

In [140]:
df["WorkExp"] = df["WorkExp"].astype(float)